### ISSUE TITLE
Datatype constraint not accepting 0000 as valid xsd:gYear value

### ISSUE THREAD

**Issue by rybesh** [TopQuadrant/shacl#10]
It seems that `0000` is not accepted as a valid value when there is a datatype constraint expecting a `xsd:gYear` value. This is probably due to the 2004 XML Schema Part 2:Datatypes Second Edition recommendation stating that [`0000` is an illegal year value](https://www.w3.org/TR/xmlschema-2/#noYearZero). However in the 2012 XML Schema Definition Language (XSD) 1.1 Part 2: Datatypes recommendation this was changed, and `0000` is now a legal value (see the note in [section D.2.1](https://www.w3.org/TR/xmlschema11-2/#vp-dt-year) of the recommendation).

On the following test case the SHACL engine detects a datatype constraint violation at `"0000"^^xsd:gYear` (which should be a legal value):

```turtle
@prefix ex: <http://example.org/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix time: <http://www.w3.org/2006/time#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

ex:YearZero
  time:hasDateTimeDescription [
    time:year "0000"^^xsd:gYear ;
  ] ;
.

ex:Apocalypse
  time:hasDateTimeDescription [
    time:year "2017"^^xsd:gYear ;
  ] ;
.

ex:DateTimeDescriptionShape
  rdf:type sh:Shape ;
  rdfs:label "Date-time description shape" ;
  sh:targetObjectsOf time:hasDateTimeDescription ;
  sh:property [
      sh:predicate time:year ;
      sh:name "year" ;
      sh:description "Gregorian calendar year" ;
      sh:datatype xsd:gYear ;
  ] ;
.
```

**Comment by HolgerKnublauch** [comment]
We use Jena's RDFDatatype.isValid function, so I have followed up on the jena-users list. http://users.jena.apache.narkive.com/pTtQtFT0/is-0-a-valid-xsd-gyear . Let's see what comes back.

**Comment by afs** [comment]
Java8, and java9, only provide XML Schema 1.0.

See JDK javadoc [`javax.xml.datatype`](https://docs.oracle.com/javase/8/docs/api/javax/xml/datatype/package-summary.html).

Apache Jena use JDK built-in classes for arithmetic.  So yes - 0000 is legal if there were support for XML Schema 1.1 but there isn't.

**Comment by HolgerKnublauch** [comment]
I could certainly patch this for gYear, but I notice the same thing would happen for xsd:date and related types, where it's a bit harder to fix. Andy, are there any plans on the Jena side to work around this? @rybesh is this based on a real-world use case, e.g. some ancient history ontology?

**Comment by afs** [comment]
It is all date datatypes related to the seven-property model.

There is no contribution or pull request waiting to go into Jena nor a change in the development branch.

What change do you propose? Validating data then failing when using it in a calculation (or producing a wrong answer for intervals across 1 CE and 1 BCE) is not a good idea either.

**Comment by rybesh** [comment]
Yes, this is a real-world use case, a gazetteer of scholarly definitions of historical, art-historical, and archaeological periods (http://perio.do). We interpret `0000` as 1 BCE, following XML Schema 1.1. We're hoping to publish SHACL shapes for our data to make it easier for us and our users to do some basic data quality checks.

**Comment by rybesh** [comment]
Apparently the 1.1 (Beta) version of Xerces supports XSD 1.1. Is it possible to configure Jena to use this rather than the JDK bundled version?

See http://stackoverflow.com/questions/20807066/how-to-validate-xml-against-xsd-1-1-in-java/31889170#31889170

**Comment by HolgerKnublauch** [comment]
Hi Ryan, as Andy stated this is quite involving because even if we work around the validation issue, it is unclear how the handling of such literals in the rest of Jena would work.

Since the discussion seems to have become a general Jena API question, I would encourage you to follow up on the Jena mailing list, and need to close the ticket here. The issue will be fixed by itself whenever either Java or Jena are updated, but I cannot really do this for SHACL only.

**Comment by afs** [comment]
I've never tried but in theory it would work. Xerces provides the `javax.xml.datatype.DatatypeFactory` as well as schema validation. Whether it has an 

For Jena uses, there is change in calculations - that may not worry you for just validation, but if you only want validation, adding tests for year "0000" in SHACL also should work.

**Comment by rybesh** [comment]
@afs I did try downloading and using the beta version of Xerces, but I ran into the problem that [Jena breaks with Xerces 2.11.0 (XML Schema 1.1 branch)](https://issues.apache.org/jira/browse/JENA-341?jql=project%20%3D%20JENA%20AND%20status%20%3D%20Open%20AND%20text%20~%20%22xerces%22%20ORDER%20BY%20priority%20DESC).

**Comment by rybesh** [comment]
For future searchers, here is the workaround I went with:
```turtle
  sh:property [
      sh:predicate time:year ;
      sh:name "year" ;
      sh:description "Gregorian calendar year" ;
      # Explicitly allow 0000 since Jena does not support XSD 1.1
      sh:or (
          [ sh:datatype xsd:gYear ; ]
          [ sh:hasValue "0000"^^xsd:gYear ; ]
      ) ;
  ] ;
```

**Comment by afs** [comment]
@rybesh - thanks for trying that out.  I'd forgotten about [JENA-341](https://issues.apache.org/jira/browse/JENA-341). My first impression is that it looks like Jena needs to isolate itself from these functions of Xerces somehow, such as taking a copy (which has had to be done before).
