### ISSUE TITLE
Shacl update rule?

### ISSUE THREAD

**Issue by mahsohn** [TopQuadrant/shacl#104]
I noticed in the shacl schema there is a sh:update sparql query type, but I've found no documentation or examples on it. I'm assuming it's not implemented in this library as I am getting a parse error and see no signs of it's implementation in the code. Can sparql updates be implemented in the rules? I believe I can add the functionality in myself but figure someone more familiar with the parser and execution engine could implement it faster.

**Comment by HolgerKnublauch** [comment]
No, rules cannot make assertions. This would add various complications such as the ability to do DELETEs which would open a can of worms such as infinite loops. I had such support in the past for SPIN but it was quite complex to implement correctly.

sh:update is in the data model/ontology for symmetry reasons and for other use cases.

What are your use cases?

**Comment by mahsohn** [comment]
I remember when spin came out there was a demo of a game made where the rules of the game were executed in sparql using spin rules. I want to do something similar to that by having shacl rules update the graph and run the rules in a loop, constantly changing the state of the graph until it reaches a conclusion. Obviously it can be dangerous to do this and I don't expect there to be safety check to avoid infinite loops, I just want the ability to overwrite existing data with shacl rules. This is definitely a non-standard use case but I think there are many cool possibilities to use shacl as a model transformation tool or even an execution engine.

**Comment by mahsohn** [comment]
Here is a simple example that I would like to test out but is not really possible, it is a rule that simply increments a number by one
```
ex:Number
  rdf:type rdfs:Class ;
  rdfs:subClassOf rdfs:Resource ;
.

ex:counter
  rdf:type ex:Number ;
  ex:value "0"^^xsd:integer;
.

ex:IncrementNumber
  rdf:type sh:NodeShape ;
  sh:rule [
      rdf:type sh:SPARQLRule ;
      sh:construct """
			CONSTRUCT {
				$this ex:value ?sum .
			}
			
			WHERE {
				$this ex:value ?value .
				FILTER (?value < 5)
				BIND (?value + 1 AS ?sum) .
			}
			""" ;
    ] ;
  sh:targetClass ex:Number ;
.
```
except I don't want to use construct, I would rather the rule look like this
```
ex:IncrementNumber
  rdf:type sh:NodeShape ;
  sh:rule [
      rdf:type sh:SPARQLRule ;
      sh:update """
			DELETE {
				$this ex:value ?value .
			}
			INSERT {
                                $this ex:value ?sum.
                        }
			WHERE {
				$this ex:value ?value .
				FILTER (?value < 5)
				BIND (?value + 1 AS ?sum) .
			}
			""" ;
    ] ;
  sh:targetClass ex:Number ;
.
```
I would then run the rules over and over until the rules have made no changes

**Comment by HolgerKnublauch** [comment]
Yes absolutely, and we are using SPARQL UPDATEs in script almost everywhere. The SHACL rule engine has its dedicated semantics though, and changing this and getting it through a community group process would be (too) hard at this stage, so I suggest you implement your own "outside loop" to iterate over the rules. The SHACL vocabulary such as sh:update could still be used to at least represent those units of work in a declarative format.

**Comment by mahsohn** [comment]
So my first thought was to extend the parser to accept update rules, are you saying there is another way? 

Also can this be done with Triple rules, the equivalent TripleRule query would be
```
ex:IncNumber
	a sh:NodeShape ;
	sh:targetClass ex:Number ;
	sh:rule [
		a sh:TripleRule ;
		sh:subject sh:this ;
		sh:predicate ex:value ;  
		sh:object [
			ex:add ( [ sh:path ex:value ] "1"^^xsd:integer ) ;
		] ;
		#sh:condition ex:Number ;   
		sh:condition [
			sh:property [
				sh:path ex:value ;
				sh:lessThan "5"^^xsd:integer ;
			] ;
		] ;
	] .
```
would I have to make a sh:updateTripleRule?

**Comment by HolgerKnublauch** [comment]
Instead of sh:updateTripleRule I would add sh:updateRule which points at an instance of sh:UpdateRule. One of its subclasses would be sh:SPARQLUpdateRule which would also be subclass of sh:SPARQLUpdateExecutable and thus inherit ui:update. Another subclass could then for TripleRules, if desired. Maybe SPARQL updates are a bit clearer and the more general solution though.

An engine could then look for sh:updateRule triples and execute them in a loop.

**Comment by mahsohn** [comment]
After tinkering around a bit, adding SPARQLRule updates to the library was relatively easy, I haven't fully tested it but here is the diff
```

diff --git a/src/main/java/org/topbraid/shacl/rules/SPARQLRule.java b/src/main/java/org/topbraid/shacl/rules/SPARQLRule.java
index 0add8f0..30b1780 100644
--- a/src/main/java/org/topbraid/shacl/rules/SPARQLRule.java
+++ b/src/main/java/org/topbraid/shacl/rules/SPARQLRule.java
@@ -23,9 +23,12 @@ import org.apache.jena.graph.Triple;
 import org.apache.jena.query.Query;
 import org.apache.jena.query.QueryExecution;
 import org.apache.jena.query.QuerySolutionMap;
+import org.apache.jena.query.QueryType;
 import org.apache.jena.rdf.model.RDFNode;
 import org.apache.jena.rdf.model.Resource;
 import org.apache.jena.rdf.model.Statement;
+import org.apache.jena.update.UpdateAction;
+import org.apache.jena.update.UpdateRequest;
 import org.apache.jena.vocabulary.RDFS;
 import org.topbraid.jenax.progress.ProgressMonitor;
 import org.topbraid.jenax.util.ARQFactory;
@@ -37,15 +40,26 @@ import org.topbraid.shacl.vocabulary.SH;
 public class SPARQLRule extends AbstractRule {

        private Query query;
+       private UpdateRequest update;


        public SPARQLRule(Resource rule) {
                super(rule);
                String rawString = JenaUtil.getStringProperty(rule, SH.construct);
-               String queryString = SPARQLSubstitutions.withPrefixes(rawString, rule);
-               query = ARQFactory.get().createQuery(queryString);
-               if(!query.isConstructType()) {
-                       throw new IllegalArgumentException("Values of sh:construct must be CONSTRUCT queries");
+               if(rawString == null) {
+                       rawString = JenaUtil.getStringProperty(rule, SH.update);
+                       String queryString = SPARQLSubstitutions.withPrefixes(rawString, rule);
+                       update = ARQFactory.get().createUpdateRequest(queryString);
+                       if(update  == null) {
+                               throw new IllegalArgumentException("Values of sh:update must be UPDATE queries");
+                       }
+               }
+               else {
+                       String queryString = SPARQLSubstitutions.withPrefixes(rawString, rule);
+                       query = ARQFactory.get().createQuery(queryString);
+                       if(!query.isConstructType()) {
+                               throw new IllegalArgumentException("Values of sh:construct must be CONSTRUCT queries");
+                       }
                }
        }

@@ -61,13 +75,18 @@ public class SPARQLRule extends AbstractRule {

                        QuerySolutionMap bindings = new QuerySolutionMap();
                        bindings.add(SH.thisVar.getVarName(), focusNode);
-                       try(QueryExecution qexec = ARQFactory.get().createQueryExecution(query, ruleEngine.getDataset(), bindings)) {
-                               Iterator<Triple> it = qexec.execConstructTriples();
-                               while(it.hasNext()) {
-                                       Triple triple = it.next();
-                                       ruleEngine.infer(triple, this, shape);
+                       if(query != null) {
+                               try(QueryExecution qexec = ARQFactory.get().createQueryExecution(query, ruleEngine.getDataset(), bindings)) {
+                                       Iterator<Triple> it = qexec.execConstructTriples();
+                                       while(it.hasNext()) {
+                                               Triple triple = it.next();
+                                               ruleEngine.infer(triple, this, shape);
+                                       }
                                }
                        }
+                       else if(update != null) {
+                               UpdateAction.execute(update, ruleEngine.getDataset(), bindings);
+                       }
                }
        }
```
Maybe you could make this a compile time feature, it could prove useful to others

**Comment by HolgerKnublauch** [comment]
Yes in principle this would work. I would probably move this into its own class sh:UpdateRule and its own Java class but the larger question is really whether this would be a candidate for the future evolution of SHACL-AF. As discussed, it's a substantial change from pure inference to "hard" rules that can directly change data. In SPIN I had to wrap the updated graph in order to keep track of whether a rule actually created new changes or whether it had reached a fixpoint, i.e. no further iterations were needed.

How do you currently (or plan) to execute this, i.e. what is the outside loop around one round of rule execution? Eg. if you increment a counter property, what is triggering the next iteration?

**Comment by mahsohn** [comment]
I'm actually getting pretty good results with that small change to the library, I simply use the ChangedListener on the model to detect changes in a while loop, if no changes have been made the loop exits. I can also do a diff on the model after every iteration.

Here's what the execution looks like

```
public static void main(String[] args) throws Exception {
        Model rules = JenaUtil.createMemoryModel();
        Model model = JenaUtil.createMemoryModel();
        InputStream rulesFile = new FileInputStream("rules.ttl");
        InputStream modelFile = new FileInputStream("model.ttl");
        rules.read(rulesFile, "urn:dummy",FileUtils.langTurtle);
        model.read(modelFile, "urn:dummy",FileUtils.langTurtle);
        
        Resource report = ValidationUtil.validateModel(model, rules, true);
        boolean conforms = report.getProperty(SH.conforms).getObject().toString().startsWith("true");
        if(conforms) {
        	System.out.println("Validation succeeded");
	        ChangedListener listener = new ChangedListener();
	        model.register(listener);
	        int maxIterations = 100;
	        int iterationCount = 0;
	        boolean changed = true;
	        long start = System.currentTimeMillis();
	        Model lastModel = model.union(JenaUtil.createMemoryModel()); //Is there a better way to copy a model?
	        SimpleProgressMonitor monitor = new SimpleProgressMonitor("progress");
	        while(changed == true && iterationCount < maxIterations) {
	        	//System.out.println("Running iteration "+iterationCount);
	        	RuleUtil.executeRules(model, rules, null, monitor);
	        	System.out.println(model.difference(lastModel));
	        	lastModel = model.union(JenaUtil.createMemoryModel());
	        	iterationCount++;
	        	changed = listener.hasChanged();
	        }
	        if(iterationCount >= maxIterations) {
	        	System.out.println("!!!Maximun iterations reached!!!"); 
	        }
	        long end = System.currentTimeMillis();
	        System.out.println("Ran " + iterationCount + " iterations taking " + (end - start) + "ms");
	        System.out.println(watches(model));
        }
        else {
        	System.out.println("Validation Failed");
        	System.out.println(report.getModel());
        }
    }
```

And it can do more than just increment a number, i'm trying to get it to execute AST nodes to use as a simple interpreter, so far it can successfully run number calculations and string manipulation, and read and write to a global store.

**Comment by HolgerKnublauch** [comment]
Yes this may make sense. I am working on other stuff right now but hope to get back to this.

**Comment by HolgerKnublauch** [comment]
A similar iteration implementation was just merged into master.
