### ISSUE TITLE
[question] an issue with a simple example

### ISSUE THREAD

**Issue by nandana** [TopQuadrant/shacl#11]
Hi,

I am trying to use TopBraid SHACL API and got an incorrect validation result. May be I am doing something wrong. Can you please have a quick look and let me know? 

Here's my data and the shape.

Data:
```
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
<http://id.nandana.org/card#me> a foaf:Person;
    foaf:age 20, 30 .
```

Shape:
```
@prefix ex: <http://example.org/shacl/> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix sh: <http://www.w3.org/ns/shacl#> .

ex:PersonShape
  a sh:NodeShape ;
  sh:property [
      sh:path foaf:age ;
      sh:maxCount 1 ;
    ] ;
  sh:targetClass foaf:Person .
```

I expected to have an validation error. But it seems the validation passes. 

```
@base          <http://example.org/random> .
@prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .
@prefix foaf:  <http://xmlns.com/foaf/0.1/> .

[ a       <http://www.w3.org/ns/shacl#ValidationReport> ;
  <http://www.w3.org/ns/shacl#conforms>
          true
] .
```

With the same inputs, in [Corese DataShape Validator](http://corese.inria.fr/), I get the following result as expected:

```
prefix rs: <http://www.w3.org/2001/sw/DataAccess/tests/result-set#>
prefix sh: <http://www.w3.org/ns/shacl#>
prefix foaf: <http://xmlns.com/foaf/0.1/>
prefix st: <http://ns.inria.fr/sparql-template/>
prefix doc: <http://w3c.github.io/data-shapes/shacl/#>

[a sh:ValidationReport ;
  sh:conforms false ;
  sh:result <urn:uuid:55e2abc0-aa76-45a3-b783-b2623938ae6e>] .

<urn:uuid:55e2abc0-aa76-45a3-b783-b2623938ae6e>
  a sh:ValidationResult ;
  sh:focusNode <http://id.nandana.org/card#me> ;
  sh:resultMessage "Fail at: [sh:maxCount 1 ;
  sh:path foaf:age]" ;
  sh:resultPath foaf:age ;
  sh:resultSeverity sh:Violation ;
  sh:sourceConstraintComponent sh:MaxCountConstraintComponent ;
  sh:value 2 .
```

Here's the code I am using:
```
        //Load the data into a model
        Model data = ModelFactory.createDefaultModel();
        data.read("personData.ttl");

        //Load the shape into a model
        Model shape = ModelFactory.createDefaultModel();
        shape.read("personShape.ttl");

        // Create Dataset that contains both the main query model and the shapes model
        URI shapesGraphURI = URI.create("urn:x-shacl-shapes-graph:" + UUID.randomUUID().toString());
        Dataset dataset = ARQFactory.get().getDataset(data);
        dataset.addNamedModel(shapesGraphURI.toString(), shape);

        Model results = new ModelConstraintValidator().validateModel(dataset, shapesGraphURI, null, true, null, null).getModel();
        System.out.println(ModelPrinter.get().print(results));
```

**Comment by HolgerKnublauch** [comment]
Hi Nandana, I believe the issue is that your shapes graph does not contain the system namespaces that it needs to "drive" the validation. The TopBraid API has nothing hard-coded, not even the constraint components. It needs to have all relevant "validators" in the shapes graph. How to do this is illustrated in the Example: https://github.com/TopQuadrant/shacl/blob/master/src/test/java/org/topbraid/shacl/ValidationExample.java

Look at lines 30 onwards, where we create the shapesGraph as a union of the graph that you have loaded plus the System triples.

**Comment by nandana** [comment]
Thanks @HolgerKnublauch !! Yep, that was the missing part. After I loaded the graphs as in SHACLSystemModel, everything worked fine.

**Comment by HolgerKnublauch** [comment]
With the latest version, I have simplified the API quite a bit, and there is now a utility method that does all this automatically. The architecture is also much cleaner now.
