### ISSUE TITLE
DoesNotCoExist - DASH Feature Request

### ISSUE THREAD

**Issue by twcook** [TopQuadrant/shacl#115]
I have a situation where I need to implement functionality similar to an XML Schema _choice_ element. 
Where if one object has a value the other must be nil.

**Comment by twcook** [comment]
I can accomplish this via other methods.

**Comment by mucaho** [comment]
Would the ``xone`` construct solve your issue?

Example from https://www.w3.org/TR/shacl/#XoneConstraintComponent :

> The following example illustrates the use of sh:xone in a shape to specify the condition that certain focus nodes must either have a value for ex:fullName or values for ex:firstName and ex:lastName, but not both. 
```sql
ex:XoneConstraintExampleShape
	a sh:NodeShape ;
	sh:targetClass ex:Person ;
	sh:xone (
		[
			sh:property [
				sh:path ex:fullName ;
				sh:minCount 1 ;
			]
		]
		[
			sh:property [
				sh:path ex:firstName ;
				sh:minCount 1 ;
			] ;
			sh:property [
				sh:path ex:lastName ;
				sh:minCount 1 ;
			]
		]
	) .
```
