### ISSUE TITLE
ability to add additional sh:message statements in addition to generated messages

### ISSUE THREAD

**Issue by bertvannuffelen** [TopQuadrant/shacl#119]
Hi,

I would like to add additional information (e.g. a validation rule number) to a SHACL constraint, but I also want to keep the generated messages.

E.g.

```
<https://data.vlaanderen.be/shacl/DCAT-AP-VL-20#CatalogusShape> a shacl:NodeShape;
  shacl:closed false;
  shacl:property [
    shacl:message "This is a title message"@en ;               
    shacl:description "De naam van de catalogus.";
    shacl:maxCount 1;
    shacl:name "titel";
    shacl:path dc:title
  ];
  shacl:targetClass dcat:Catalog 
```

will overwrite the default generated error message "Property may only have 1 value, but found 2" with " This is a title message". 

Is there a way to have both messages as sh:resultMessage?

Because it is a pity that the generated messages cannot be translated, nor be used in addition with business messages as they contain information that cannot be know at the time of configuring the constraint.  An alternative would be that the variables used to compose the generated messages with are available for building your own messages.

**Comment by JohannesLipp** [comment]
I am not sure about the implementation in the TopQuadrant SHACL validator, but the SHACL docs allow multiple `sh:messages` as long as they have different language tags (cf. https://www.w3.org/TR/shacl/#message).

Could you test adding one or more messages in different languages? English is probably default, which will override the default validation report message, so better try something else?

**Comment by bertvannuffelen** [comment]
@JohannesLipp 

I tried it but it still overwrites. But even if that worked, would my request stand. 

In the mean time I found out that if I assign a URI to my propertyshape (instead of the above anonymous node), I get that URI back as the sh:sourceShape. If I assign to that URI the message as rdfs:label, then an application could dereference that URI and find my message.

It feels like a work-around, but probably this is the cleanest approach.

**Comment by JohannesLipp** [comment]
Thanks for sharing this! This indeed feels like a work-around; let's see if someone else proposes a better approach.

**Comment by HolgerKnublauch** [comment]
I don't see another alternative here. As you can see in the source code, the default messages are hard-coded and in English. As soon as the shape declares one sh:message, then those message(s) will be used instead, replacing the default message.

If the English messages don't work for you, you could write a post-processor that takes the validation report and *adds* additional sh:resultMessages, e.g. in Dutch. this could use the pointer to the constraint component to determine what should go into the message.

**Comment by bertvannuffelen** [comment]
@HolgerKnublauch  
> 
> I don't see another alternative here. As you can see in the source code, the default messages are hard-coded and in English. As soon as the shape declares one sh:message, then those message(s) will be used instead, replacing the default message.
> 
Is this a implementation feature or by the SHACL specification design?

> If the English messages don't work for you, you could write a post-processor that takes the validation report and _adds_ additional sh:resultMessages, e.g. in Dutch. this could use the pointer to the constraint component to determine what should go into the message.

It is not that the engine messages worthless, actually I would like to keep them and extend/add other messages to them because they contain information that cannot be retrieved otherwise.

But as I understand from your explanation, I will implement my last approach.
Thanks for the feedback.

**Comment by HolgerKnublauch** [comment]
The spec states that IF values for sh:message exist then they must be used, see https://www.w3.org/TR/shacl/#message and they must be "exactly" those values, i.e. no other values should exist.

But also note that it SHOULD not have more than one value in the same language, so leaving the default message plus something else would not follow best practices. So we pick one or the other. (You may of course trick this a bit by using a plain xsd:string plus an rdf:langString in, say, "en-US" but a tool will usually only display one of these values. Better produce a new resultMessage that concatenates the original message plus your extra text).

If this is now clear, feel free to close this ticket.
