### ISSUE TITLE
Error occurs when using "prefix :" with sequence path

### ISSUE THREAD

**Issue by joylix** [TopQuadrant/shacl#121]
My environment is  windows 10 , when I run [SHACL Test Suite: path-sequence-001](https://github.com/w3c/data-shapes/blob/gh-pages/data-shapes-test-suite/tests/core/path/path-sequence-001.ttl) , it is OK,  But when I replace "prefix ex:" with "prefix :" I get an error message:  
         _`Unresolved prefixed name: :property1`_
I don't know if my test environment caused the error, or "prefix :" is not supported.

**Comment by HolgerKnublauch** [comment]
Can you attach the file that you have tried? I suspect an RDF syntax error.

**Comment by joylix** [comment]
I just split https://github.com/w3c/data-shapes/blob/gh-pages/data-shapes-test-suite/tests/core/path/path-sequence-001.ttl into two separate file,  data.ttl and shacl.ttl, the results were completely normal,
[data.ttl.txt](https://github.com/TopQuadrant/shacl/files/7073832/data.ttl.txt)
[shacl.ttl.txt](https://github.com/TopQuadrant/shacl/files/7073834/shacl.ttl.txt)
 then I replace "prefix ex:" with "prefix :", The representation in the corresponding data also replaces "ex:" with ":",  and then things go wrong. I believe that RDF syntax is error-free.
[data2.ttl.txt](https://github.com/TopQuadrant/shacl/files/7073859/data2.ttl.txt)
[shacl2.ttl.txt](https://github.com/TopQuadrant/shacl/files/7073860/shacl2.ttl.txt)

**Comment by HolgerKnublauch** [comment]
The files look syntactically correct. With the provided information I have no idea what is wrong, but this W3C issue tracker does not sound like the right place to resolve this.

**Comment by joylix** [comment]
It doesn't bother me that much, so I just avoid using "prefix :" .  I used to use "prefix :" up until now, so it really puzzled me for a long time before I figured it out.  
Thanks.

**Comment by afs** [comment]
#112
