### ISSUE TITLE
Writing SHACLC broken

### ISSUE THREAD

**Issue by afs** [TopQuadrant/shacl#124]
Previous fixes are not present.

Output is now:
```
shape ex:PersonShape targetClass=ex:Person { }
```
was, and should be:
```
shape ex:PersonShape -> ex:Person { }
```
Other fixes also missing.

**Comment by afs** [comment]
Commit ddb0ad09d8. 

I don't _need_ this - Apache Jena has a SHACL Compact reader/writer with a test suite. The fix was for this repos benefit.

> Do you have specific use case

I do see large collection of shapes for validation (going with large ontologies). They make use of only the term constraints and cardinality. I don't see the OWL-related-features of SHACL ever used. 

Obviously validation-only is less than TopQuadrant's whole interest but "out there", validation is the primary UC.

SHACLC often covers the validation in a form that is easy for humans to work with and integrate into process devops pipelines.
The RDF syntax makes it harder to work with at scale for maintainance and enhancement. (Not everyone has a copy of Topquadrant EDG.)

**Comment by HolgerKnublauch** [comment]
Ok thanks for clarifying. I have removed our own SHACLC implementation. There is no point in maintaining two, and my implementation had introduced a rather ugly dependency to ANTLR. Those who want to use SHACLC can bring in jena-shacl.

(And yes I agree it's potentially a useful syntax. I only remain unconvinced that many people will generate SHACLC programmatically vs hand-editing)

**Comment by griddigit** [comment]
Hi
Thanks would 1.4.1 release will also go to Maven?
