### ISSUE TITLE
data graph and ontology axioms

### ISSUE THREAD

**Issue by justin2004** [TopQuadrant/shacl#125]
["The data graph is expected to include all the ontology axioms related to the data and especially all the rdfs:subClassOf triples in order for SHACL to correctly identify class targets and validate Core SHACL constraints."](https://www.w3.org/TR/shacl/#data-graph).

So that means if you want to validate a data.ttl file but not validate an ont.ttl file (with your ontology axioms) you cannot.

e.g.

ont.ttl (we need the rdfs:subClassOf triples)
```
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix ex: <http://bob.com/> .

ex:Contract rdfs:subClassOf ex:Agreement .
ex:Person rdfs:subClassOf ex:Agent .
# ex:Agent == "one that acts or exerts power"

ex:entities\/Deed1 a ex:Agreement ;
   rdfs:comment "this is the deed to the ontology creator's house" .
```

data.ttl
```
@prefix dash: <http://datashapes.org/dash#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix schema: <http://schema.org/> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix ex: <http://bob.com/> .

ex:thing1 a ex:Agreement ;
   ex:party ex:Fred .

ex:Fred a ex:Person .
```

shape.ttl
```
@prefix dash: <http://datashapes.org/dash#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix schema: <http://schema.org/> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix ex: <http://bob.com/> .
@prefix gist: <https://ontologies.semanticarts.com/gist/> .

ex:AgreementShape a sh:NodeShape ;
 sh:targetClass ex:Agreement ;
 sh:property [
  sh:path ex:party ;
  sh:minCount 1 ;
  sh:class ex:Agent ] .
```

then at the shell
```
~/Downloads/apache-jena-4.2.0/bin/riot ./data.ttl ./ont.ttl > data_plus_ontology_axioms.ttl
docker run --rm -it -v `pwd`:/mnt justin2004/shacl_box ./shaclvalidate.sh -datafile /mnt/data_plus_ontology_axioms.ttl -shapesfile /mnt/shape.ttl
@prefix schema: <http://schema.org/> .
@prefix ex:    <http://bob.com/> .
@prefix gist:  <https://ontologies.semanticarts.com/gist/> .
@prefix owl:   <http://www.w3.org/2002/07/owl#> .
@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix sh:    <http://www.w3.org/ns/shacl#> .
@prefix tosh:  <http://topbraid.org/tosh#> .
@prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
@prefix dash:  <http://datashapes.org/dash#> .
@prefix swa:   <http://topbraid.org/swa#> .

[ a            sh:ValidationReport ;
  sh:conforms  false ;
  sh:result    [ a                             sh:ValidationResult ;
                 sh:focusNode                  <http://bob.com/entities/Deed1> ;
                 sh:resultMessage              "Property needs to have at least 1 value" ;
                 sh:resultPath                 ex:party ;
                 sh:resultSeverity             sh:Violation ;
                 sh:sourceConstraintComponent  sh:MinCountConstraintComponent ;
                 sh:sourceShape                [] 
               ]
] .
```

So ont.ttl got validated but we don't want it to be validated. We only want to use it for ontology axioms (like rdfs:subClassOf triples).

Should SHACL do one of the following?
a) recognize another graph kind: "axiom graph"
b) allow the ontology axioms to be in the shapes graph so they aren't subject to validation

**Comment by HolgerKnublauch** [comment]
The spec states you only need the relevant axioms, i.e. in this case the rdfs:subClassOf triples. Not the whole ontology graph. So depending on what input you give the processor, you still have that level of control. I would consider it unusual for the ontology graph to also hold instances.

While the command line processor does not have that option, the API can be used to validate individual instances programmatically, e.g. based on only the locally defined subjects of the real data graph.

**Comment by justin2004** [comment]
>  you only need the relevant axioms

what are all the relevant axioms? just `rdfs:subClassOf` triples?
if they are enumerated somewhere then we could run a construct query to extract just the relevant triples.

**Comment by HolgerKnublauch** [comment]
From the top of my head you need rdfs:subClassOf and the rdf:type triples of all classes, in case you are using classes that are also node shapes. But you can drop any rdfs:domain/range/OWL axioms. So yes, a CONSTRUCT should be doable.

**Comment by justin2004** [comment]
thanks.

> I would consider it unusual for the ontology graph to also hold instances.

there are ontologies out there that hold instances such as currencies (i think Gist does that).

**Comment by HolgerKnublauch** [comment]
Yes, such examples exist and sometimes it even makes sense.

Feel free to close the ticket if your questions have been answered.

**Comment by justin2004** [comment]
i still think it would make sense to distinguish between the data, shapes, and axioms graphs.

another reason to do it would be to allow a `sh:query` to use the axiom triples (from an ont.ttl file). right now the only way to do that is to allow validation to run over an ont.ttl file.

**Comment by HolgerKnublauch** [comment]
In practice we typically only validate the subjects mentioned in the base graph, ignoring the owl:imported graphs. This solves this problem too.

On further discussions, you may want to join the new SHACL Discord channels, where there is a channel for potential SHACL 1.1 features.

**Comment by afs** [comment]
In Jena, you can have inference without the ontology data being visible. Again, that needs API setup.

**Comment by justin2004** [comment]
I learned today that [Stardog](https://docs.stardog.com/archive/7.7.3/stardog-cli-reference/icv/icv-report) allows you to do apply SHACL validation:

- to a named graph(s)
- using ontology axioms (that you specify in a named graph)
- using a shapes file that you specify.

All from the CLI.

So it distinguishes between axioms graphs, data graphs, and shapes graphs.
