### ISSUE TITLE
No logging

### ISSUE THREAD

**Issue by afs** [TopQuadrant/shacl#130]
The command line tools have no logging. Warnings about bad URIs are thrown away.

The scripts have `-Dlog4j.configuration=file:$SHACL_HOME/log4j.properties` but that's the log4j1 system property and `log4j.properties` is a log4j1 properties file.

Which doesn't matter because there are no log-anything jars files in the lib/ directory of the zip file or the runtime classpath.

**Comment by afs** [comment]
`org.apache.logging.log4j:log4j-slf4j-impl` is in scope test.

**Comment by HolgerKnublauch** [comment]
Thanks, Andy. I had not updated this for a long time, still using what I found in older versions of Jena. I hope it's better now.

**Comment by afs** [comment]
Jena libs don't choose the logging. The concrete logging is added in jena-cmds and Fuseki.
