### ISSUE TITLE
Does SHACL library support sh:targetShape or sh:filterShape?

### ISSUE THREAD

**Issue by beaudet** [TopQuadrant/shacl#134]
I have a number of crm:E22_Human-Made_Objects that can be categorized as falling into three main sub-types:
* top level object (not a part of another human made object) - some properties are required that are not required of regular objects
* regular object (has a parent object) - some required properties but not as many as toplevel
* external reference - lacking most properties so very few required

Currently, I'm using sh:or to short-circuit the cases that don't apply to certain shapes, but it would be a lot cleaner IMHO to define shape selectors and use them as targets.  I'm sure I can get this working with SPARQLTarget, but it would be great to use an sh:Shape to define the targets interest.

I've tried targetShape but it seems that custom target would need to be implemented as a contribution - and presumably it's not core SHACL, but then again neither is SPARQLTarget either right?  What about sh:filterShape?  I tried that as well, but couldn't get it working with this SHACL library - for example, I've tried the following (didn't work) that on the surface seems like it should start with all E22, keep only the ones with an la:equivalent predicate, and then validate those to see if they contain the label "Mona Lisa".  The validation report seems to indicate that no filtering is happening since I'm getting results for E22s both with and without la:equivalent predicates.

Is there any way to do this sort of thing with shapes using this SHACL library or should I switch to SPARQLTarget instead?  

```
la:someFilter
    a sh:Shape;
    sh:targetClass crm:E22_Human-Made_Object;
    sh:filterShape [
        sh:property [
            sh:path la:equivalent;
            sh:pattern ".?";
        ];
    ];
    sh:property [
        sh:path rdfs:label;
        sh:hasValue "Mona Lisa";
    ];
.
```

**Comment by beaudet** [comment]
For example, this works fine:

```
la:toplevelObjectTarget
    a sh:SPARQLTarget;
    sh:select """
        prefix crm:     <http://www.cidoc-crm.org/cidoc-crm/>
        prefix la:      <https://linked.art/ns/terms/>
        SELECT ?this
        WHERE {
            ?this a crm:E22_Human-Made_Object .

            # top level objects don't have a parent
            filter not exists { ?s crm:P46_is_composed_of ?this }
            filter not exists { ?s la:equivalent ?this }
        }
    """ ;
.

la:testit
    a sh:Shape;
    sh:target la:toplevelObjectTarget;
    sh:property [
        sh:path rdfs:label;
        sh:hasValue "stuff";
    ];
.
```

**Comment by beaudet** [comment]
In my opinion, it would be tidier to use something like this, if it could be supported:

```
la:toplevelObjectTarget
    a sh:PropertyShape;
    sh:class crm:E22_Human-Made_Object;
    sh:not ( sh:path [ sh:inversePath la:equivalent ] );
    sh:not ( sh:path [ sh:inversePath crm:P46_is_composed_of ] );
.

la:testit
    a sh:Shape;
    sh:target la:toplevelObjectTarget;
    sh:property [
        sh:path rdfs:label;
        sh:hasValue "stuff";
    ];
.
```

**Comment by HolgerKnublauch** [comment]
I believe you may want to join the SHACL Discord community, esp the SHACL 1.1 channel there. Prior to that challen, we had extensive discussions on the public-shacl mailing list about something very similar, see https://lists.w3.org/Archives/Public/public-shacl/2020Jun/0005.html

This topic isn't really suitable for discussion as an issue on our open source project, but rather about SHACL in general and how targeting works. So I'll close this ticket if you don't mind.

**Comment by HolgerKnublauch** [comment]
https://twitter.com/HolgerKnublauch/status/1461590465304662019

**Comment by afs** [comment]
And/or open the "discussions" feature of the repo. The headline question is asking about this library.

**Comment by beaudet** [comment]
Yeah, that's totally fine to close, although how would you prefer that questions are asked about feature support, such as if sh:filterShape is supported by this library?

**Comment by HolgerKnublauch** [comment]
sh:filterShape is a SHACL Node Expression, see https://w3c.github.io/shacl/shacl-af/#node-expressions-filter-shape which is something rather different from what you mean here. Earlier versions of SHACL used sh:filterShape differently, and we also no longer use sh:Shape but rather sh:NodeShape.

**Comment by beaudet** [comment]
Thanks for that.  As an obviously new SHACL user, it's been pretty hard to find good SHACL documentation that's not out of date (the "validating RDF" book on SHACL is based on the previous version) and the specs are... well... not so readable, even if they are exact for the benefit of solid implementations.  It would be awesome to populate the wiki of this project with links to some collections of up-to-date SHACL examples of such a treasure trove exists.
