### ISSUE TITLE
Generate SHACL shapes from ontology axioms

### ISSUE THREAD

**Issue by Remya-Ramachandran** [TopQuadrant/shacl#155]
Given an ontology (.owl file), does the tool provide functionality to generate SHACL shapes from ontology axioms

**Comment by tfrancart** [comment]
No I don't think so. SHACL Play at https://shacl-play.sparna.fr/play/ does offer this kind of OWL to SHACL conversion, based on 3 different set of conversion rules at https://github.com/sparna-git/owl2shacl
