### ISSUE TITLE
exit with error if no shacl_home

### ISSUE THREAD

**Issue by majidaldo** [TopQuadrant/shacl#156]
https://github.com/TopQuadrant/shacl/blob/fa6627b44d76d9d2bc773291ddc0551979c39923/src/main/command/shaclinfer.bat#L10

https://github.com/TopQuadrant/shacl/blob/master/src/main/command/shaclvalidate.bat#L10

**Comment by HolgerKnublauch** [comment]
Sorry I have no Windows machine to run .bat files anymore. Could you elaborate what is wrong here?

**Comment by majidaldo** [comment]
> Sorry I have no Windows machine to run .bat files anymore. Could you elaborate what is wrong here?

the script should set an error code on exit.

https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/exit

**Comment by HolgerKnublauch** [comment]
And which error code? Could you just tell me what change you want please?

**Comment by majidaldo** [comment]
> And which error code? Could you just tell me what change you want please?

you can use 1. it should match the bash scripts.
```
❯ echo %errorlevel%
0
❯ call .\error.bat
echo "this is an error"
"this is an error"
exit /b 1
❯ echo %errorlevel%
1
```

**Comment by HolgerKnublauch** [comment]
Ok thanks, does this change address it?

**Comment by majidaldo** [comment]
closing this one in particular but .sh scripts should also have  exit codes.
