### ISSUE TITLE
urns with slashes should be ok

### ISSUE THREAD

**Issue by majidaldo** [TopQuadrant/shacl#164]
https://datatracker.ietf.org/doc/html/rfc8141
```
21:43:15 WARN  riot       :: [line: 43843, col: 66] Bad IRI: <urn:ex/supplyAirOutlet> Code: 61/SCHEME_PATTERN_MATCH_FAILED in PATH: The scheme specific syntax rules are violated.
```

( found this in stdout. [related](https://github.com/TopQuadrant/shacl/issues/157), )

**Comment by HolgerKnublauch** [comment]
I think URNs need at least two : characters

**Comment by majidaldo** [comment]
> I think URNs need at least two : characters

indeed! thanks!
