### ISSUE TITLE
Using Sequence and Inverse Path together

### ISSUE THREAD

**Issue by ensaremirerol** [TopQuadrant/shacl#165]
Hi,

We are using SHACL to run data validation (these rules contains some consistency and logical rules) on RDF data. We are using [SPHN](https://biomedit.ch/rdf/sphn-schema/sphn) ontology and we are having problems because of its structure.

SPHN has a class named [Subject Pseudo Identifier](https://biomedit.ch/rdf/sphn-schema/sphn#SubjectPseudoIdentifier) whose has sole purpose of identifying one person. This node may point to the its data provider or alternative identifiers and every other object points to the Subject Pseudo Identifier.

Because of this structure writing rules that check more than one class is a quite a challenge.

# Example Case

Writing a SHACL shape that throws error to the RDF bellow

## RDF

```turtle
@prefix sh: <http://www.w3.org/ns/shacl#> . # W3C Shapes Constraint Language (SHACL) Vocabulary
@prefix dash: <http://datashapes.org/dash#> . # DASH Data Shapes Vocabulary
@prefix ex: <http://example.org/> .
@prefix test: <http://example.org/test/> .
@prefix sphn: <https://biomedit.ch/rdf/sphn-ontology/sphn#> .
@prefix ICD10: <http://id.who.int/icd/release/10/> .
@prefix snomedct: <http://purl.bioontology.org/ontology/SNOMEDCT/> .

test:id1 a sphn:SubjectPseudoIdentifier .

test:male a sphn:AdministrativeGender ;
    sphn:hasCode snomedct:248153007 ;
    sphn:hasSubjectPseudoIdentifier test:id1 .

test:diagnosis1 a sphn:Diagnosis ;
    sphn:hasCode ICD10:C55 ;
    sphn:hasSubjectPseudoIdentifier test:id1 .
```
## Visualization

![image](https://github.com/TopQuadrant/shacl/assets/49997997/ad8eb48a-e95c-4cb5-bf36-8d08e8e164c6)

## What I tried
In my attempts I mostly tried to use Subject Pseudo Identifier as targetClass 

### Subject Pseudo Identifier as targetClass

```turtle
@prefix sh: <http://www.w3.org/ns/shacl#> . # W3C Shapes Constraint Language (SHACL) Vocabulary
@prefix dash: <http://datashapes.org/dash#> . # DASH Data Shapes Vocabulary
@prefix ex: <http://example.org/> .
@prefix test: <http://example.org/test/> .
@prefix sphn: <https://biomedit.ch/rdf/sphn-ontology/sphn#> .
@prefix ICD10: <http://id.who.int/icd/release/10/> .
@prefix snomedct: <http://purl.bioontology.org/ontology/SNOMEDCT/> .

ex:ICD_C55_Gender_dx_constraint a sh:NodeShape ;
    sh:targetClass sphn:SubjectPseudoIdentifier ;
    sh:not [
        sh:and (
            [
                sh:path ([sh:inversePath sphn:hasSubjectPseudoIdentifier ] sphn:hasCode) ; # ???
                sh:in (ICD10:C55)
            ]
            [
                sh:path ([sh:inversePath sphn:hasSubjectPseudoIdentifier ] sphn:hasCode) ;
                sh:in (snomedct:248153007)
            ]
        )
    ] .
```

As you can see, I tried to use inverse path in path sequence which seems like it does not work. Also one other problem with this approach is every class connects to Subject Pseudo Identifier with hasSubjectPseudoIdentifier predicate. That means these two condition would scan all of the classes which is not ideal.

I thought about starting from one of the other classes(Diagnosis or AdministrativeGender) but couldn't figure out how to do it and again, we probably need to use sequence and inverse paths together to check the other class.

So my question is "Is it possible to use Sequence and Inverse path together? Or do you have solution to the case we have in our hands?"

Thanks!

**Comment by HolgerKnublauch** [comment]
In general, yes, it is possible to use sequence and inversePath together.

But I am not sure what constraint you actually want to enforce, i.e. where is the violation? I am not familiar with SPHN.

The shape above does not look right though: there is a (top-level) NodeShape which uses a sh:and to point at property shapes. But property shapes need to be values of sh:property, so maybe you mean

ex:ICD_C55_Gender_dx_constraint a sh:NodeShape ;
    sh:targetClass sphn:SubjectPseudoIdentifier ;
    sh:not [
        sh:property [
                sh:path ([sh:inversePath sphn:hasSubjectPseudoIdentifier ] sphn:hasCode) ; # ???
                sh:in (ICD10:C55)
            ] ;
        sh:property [
                sh:path ([sh:inversePath sphn:hasSubjectPseudoIdentifier ] sphn:hasCode) ;
                sh:in (snomedct:248153007)
            ]
    ] .

Also please note this is the GitHub repo for the TopBraid SHACL API, but not a general place to find answers to SHACL modeling questions. You may reach more people on places like the SHACL discord server https://lists.w3.org/Archives/Public/public-shacl/2021Nov/0007.html

**Comment by ensaremirerol** [comment]
Thanks for letting me know. I didn't know there was a Discord Server dedicated to SHACL. Also I think there is a problem with using Inverse paths in sequences. Because I couldn't get it to work even the basic shapes.

```turtle
@prefix sh: <http://www.w3.org/ns/shacl#> . # W3C Shapes Constraint Language (SHACL) Vocabulary
@prefix dash: <http://datashapes.org/dash#> . # DASH Data Shapes Vocabulary
@prefix ex: <http://example.org/> .
@prefix test: <http://example.org/test/> .
@prefix sphn: <https://biomedit.ch/rdf/sphn-ontology/sphn#> .
@prefix ICD10: <http://id.who.int/icd/release/10/> .
@prefix snomedct: <http://purl.bioontology.org/ontology/SNOMEDCT/> .

ex:test_shape_from_subjectPseudoIdentifier a sh:NodeShape ;
    sh:targetClass sphn:SubjectPseudoIdentifier ;
    sh:not[
        sh:property [
            sh:path ([sh:inversePath sphn:hasSubjectPseudoIdentifier] sphn:hasCode) ;
            sh:in (snomedct:248153007) ;
        ] ;
    ].

ex:test_shape_from_gender a sh:NodeShape ;
    sh:targetClass sphn:AdministrativeGender ;
    sh:not[
        sh:property [
            sh:path sphn:hasCode ;
            sh:in (snomedct:248153007) ;
        ] ;
    ].
```

When I use the shapes above I can only get violation on the second one(test_shape_from_gender). You can see the report bellow.

```turtle
@prefix ICD10:    <http://id.who.int/icd/release/10/> .
@prefix dash:     <http://datashapes.org/dash#> .
@prefix ex:       <http://example.org/> .
@prefix graphql:  <http://datashapes.org/graphql#> .
@prefix owl:      <http://www.w3.org/2002/07/owl#> .
@prefix rdf:      <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs:     <http://www.w3.org/2000/01/rdf-schema#> .
@prefix sh:       <http://www.w3.org/ns/shacl#> .
@prefix snomedct: <http://purl.bioontology.org/ontology/SNOMEDCT/> .
@prefix sphn:     <https://biomedit.ch/rdf/sphn-ontology/sphn#> .
@prefix swa:      <http://topbraid.org/swa#> .
@prefix test:     <http://example.org/test/> .
@prefix tosh:     <http://topbraid.org/tosh#> .
@prefix xsd:      <http://www.w3.org/2001/XMLSchema#> .

[ rdf:type     sh:ValidationReport ;
  sh:conforms  false ;
  sh:result    [ rdf:type                      sh:ValidationResult ;
                 sh:focusNode                  test:male ;
                 sh:resultMessage              "Value has shape _:eb2c69447c6e30fe4e25de226f220896" ;
                 sh:resultSeverity             sh:Violation ;
                 sh:sourceConstraintComponent  sh:NotConstraintComponent ;
                 sh:sourceShape                ex:test_shape_from_gender ;
                 sh:value                      test:male
               ]
] .
```

If you think this is a bug you can keep the issue open I would love to follow up on this but I have no idea to where to start.
But if you think this is intended behavior then you can close the issue.

I will also ask the same question on Discord as well (with some more clarification)

**Comment by HolgerKnublauch** [comment]
The path executes as

    SELECT ?code
    WHERE {
        test:id1 ^<https://biomedit.ch/rdf/sphn-ontology/sphn#hasSubjectPseudoIdentifier>/<https://biomedit.ch/rdf/sphn-ontology/sphn#hasCode> ?code .
    }

which returns both codes. But then the sh:not condition files because not all values are in the given sh:in list.

To me it looks correct and as expected.

**Comment by ensaremirerol** [comment]
Yeah you are right, as you said it works as expected. There was a problem with my approach. Sorry
