### ISSUE TITLE
JS impl: message not useful for sh:in list

### ISSUE THREAD

**Issue by VladimirAlexiev** [TopQuadrant/shacl#20]
Go to http://shacl.org/playground/, select "example in Turtle" and add
```ttl
schema:gender "hermaphrodite"
```

This constraint:
```ttl
    sh:property [
        sh:path schema:gender ;
        sh:in ( "female" "male" ) ;
    ] ;
```
Causes this result:
```ttl
[
	a sh:ValidationResult ;
	sh:resultSeverity sh:Violation ;
	sh:sourceConstraintComponent sh:InConstraintComponent ;
	sh:sourceShape _:n3 ;
	sh:focusNode <http://example.org/ns#Bob> ;
	sh:value "hermaphrodite" ;
	sh:resultPath schema:gender ;
	sh:resultMessage "Value is not in Blank node _:n11" ;
] .
```
"Blank node _:n11" in `sh:resultMessage` is not very useful.

**Comment by VladimirAlexiev** [comment]
I guess this issue should be against https://github.com/TopQuadrant/shacl-js? Sorry about that, saw taht repo after posting

**Comment by HolgerKnublauch** [comment]
Yes please clone this issue into shacl-js (which we recently separated from this shacl project). The error message does render better in the Java API.
