### ISSUE TITLE
Add standard Apache License headers to files.

### ISSUE THREAD

**Issue by afs** [TopQuadrant/shacl#24]
The java and POM file should have license headers.  
We can automate checking of this using the Apache Creadur RAT plugin.

**Comment by HolgerKnublauch** [comment]
Note that my workflow so far has been to periodically copy the .java files from our internal TopBraid code base into the public repo. So if you're doing changes here, they need to be copied over into our private repo, or they may be overwritten (I can take care of that, of course).

**Comment by afs** [comment]
I can script applying license headers for most files so even if they get lost or mangled, they can be reapplied.

We ought to do that for java files - that should be adequate for a first central.maven release.  We ought to add to TTL files (this can be a two line short form for short files) but I don't see it a blocker for a first release to central.maven.

shacl-validator.js has old license text. Fixed: https://github.com/TopQuadrant/shacl/commit/bf8cae795e83d1ff6b41a54aed5cc91897be5e82

**Comment by afs** [comment]
Done for `org.topbraid.shacl`. See https://github.com/TopQuadrant/shacl/commit/80d9a179ff305ff9219ffe60c3c1fb6df7b775bf.

What's the status of `org.topbraid.spin` in this repository?

**Comment by HolgerKnublauch** [comment]
Thanks, I have also copied your changes back into our internal repo, to avoid accidental overwrites.

I presume since the spin packages are part of this project here, they need to have the same license.

**Comment by afs** [comment]
Easy enough to do there as well.

Would it be useful to rename as `opg.topbraid.spin` as `org.topbraid.spinx`, or somesuch, to rename them apart from the SpinRDF itself?

**Comment by HolgerKnublauch** [comment]
I see no reason to rename the org.topbraid.spin packages - it would just complicate the code maintenance as we would need different versions of the SHACL java files between TopBraid private repo and this public one.
