### ISSUE TITLE
Note W3C-licensed materials

### ISSUE THREAD

**Issue by afs** [TopQuadrant/shacl#25]
Are any of the files copied or derived from W3C published material?  (The W3C Software License will apply).

**Comment by HolgerKnublauch** [comment]
This should be the only W3C file: https://github.com/TopQuadrant/shacl/blob/master/src/main/resources/etc/shacl.ttl (taken from the SHACL namespace document)

**Comment by afs** [comment]
Added a comment to acknowledge the W3C License:

https://github.com/TopQuadrant/shacl/commit/760122a614517d9beb5e936694837d5ea9f1718a
