### ISSUE TITLE
Required parameters of SPARQL-based Constraint Components

### ISSUE THREAD

**Issue by m0squito** [TopQuadrant/shacl#29]
First of all, this is more of a question rather than an issue and I apologize if this is a wrong venue to post it (what would be a better place for it?).

I defined a SPARQL-based component with two parameters, neither of which is optional. When I use this component in a shape but provide only one parameter, the shape is simply ignored by the API. It only works when I provide both required parameters.

Is there any mechanism to create a warning that the shape definition lacked a required parameter? I also tried using DASH `dash:coExistsWith`, but it didn't change anything.

**Comment by HolgerKnublauch** [comment]
A better place for this question (to improve its visibility) would be the SHACL community group. If you don't mind, could you try posting it there - apparently you don't need to join that CG to post. https://lists.w3.org/Archives/Public/public-shacl/

**Comment by m0squito** [comment]
Thanks, @HolgerKnublauch, that is what I was looking for. Actually, I was already a member of the CG, but forgot about it ;-)
