### ISSUE TITLE
Result of inferred triples

### ISSUE THREAD

**Issue by imaneelarabi** [TopQuadrant/shacl#31]
I tried some inference rules on my data file, and i was wondering if the inferred triples are supposed to be stored in my data file by default or should i add them there myself? 
So far, I have been able to get the result and display it using the following commands: 

Model results = RuleUtil.executeRules(dataModel, shapesModel, null, null);
results.write(System.out, FileUtils.langTurtle);

**Comment by HolgerKnublauch** [comment]
The SHACL rule engine just creates new triples in a Jena Model/Graph. RuleUtil produces a new Model, and the source graphs are not modified. Whether and where you want to persist them is the choice in your own code.

**Comment by imaneelarabi** [comment]
Ok thank you!
