### ISSUE TITLE
jenax directory not included in version 1.0.1

### ISSUE THREAD

**Issue by tomide1** [TopQuadrant/shacl#33]
I added the org.topbraid shacl dependency to an IntelliJ maven project and found only the shacl and spin directories in the downloaded jar file but not jenax. However, it seems I'll need jenax to validate an rdf:turtle data-graph following the example in shacl/src/test/java/org/topbraid/shacl/ValidationExample.java. 
![topbraid shacl](https://user-images.githubusercontent.com/11017392/36906273-609cd3e0-1e2d-11e8-88d8-a2196f602d25.png)

**Comment by HolgerKnublauch** [comment]
The link to the example points at the master branch (work in progress), while the .jar release was produced with an older version. If you want to use exactly the same code from the example, clone the project and build a new .jar yourself. Alternatively, use the version from the src code matching the .jar file from https://github.com/TopQuadrant/shacl/archive/shacl-1.0.1.zip

We will publish a proper 1.1 release hopefully soon.
