### ISSUE TITLE
Notify when no shapes are selected for validation

### ISSUE THREAD

**Issue by umbreak** [TopQuadrant/shacl#38]
I'm not sure if this is in the SHACL spec, however is on our use case.

We want to know when **no shape was selected for validation**. From the output of `ValidationUtil.validateModel(...)` we cannot access any of this information (the report says it passes if, for instance, the main `targetClass` is not selected).

The way we went for now is to extend the `ValidationEngine` with the following method:
```java
public Boolean shapesSelected() {
    List<Shape> rootShapes = shapesGraph.getRootShapes();
    for(Shape shape : rootShapes)
        if(!SHACLUtil.getTargetNodes(shape.getShapeResource(), dataset).isEmpty()) 
            return false;
    return true;
}
```

After that we built the `validateModel` first calling this `shapesSelected()` first and returning some appropriate `Resource` response when there are no shapes selected for validation.

Would something like that be useful to implement upstream? If not, is this the best way to check if nothing is selected for validation?

Thanks in advance

**Comment by tfrancart** [comment]
May be related to #6

**Comment by HolgerKnublauch** [comment]
The function looks about right. Compare with ValidationEngine.validateAll(): You may want to skip shapes that are deactivated or that may be ignored, such as in

`if(!shapesGraph.isIgnored(shape.getShapeResource().asNode()) && !shape.getShapeResource().isDeactivated()) {`

Likewise there may be shapes that do not have any constraints, if that's another corner case of interest - there could be target nodes for them yet they could never cause violations.

**Comment by umbreak** [comment]
I will use the protected `validateNodesAgainstConstraint ` in order to implement this.
