### ISSUE TITLE
Report information not exhaustive

### ISSUE THREAD

**Issue by umbreak** [TopQuadrant/shacl#39]
It would be very nice if we can call validation with a flag that will output more detailed report validations.

I understand that it is implemented this way for performance, but for people doing data modeling it is much easier to have a comprehensive report message. I'm talking about the errors like `AndConstraintComponent` , `OrConstraintComponent` and `NodeConstraintComponent` (maybe I'm missing some). If it continues analysing down to the actual `properties`, the report becomes much more readable and easy to spot the error on your data.

**Comment by umbreak** [comment]
Checking on the master branch, I realised that this might be addressed by the `ValidationEngineConfiguration.validationErrorBatch` ? If so, you can close the issue

**Comment by HolgerKnublauch** [comment]
I agree this would be useful. The property to use would be sh:detail. I already have an (internal) JIRA ticket on this topic and have increased its priority after your request. I will hopefully get it done in the next couple of weeks. (validationErrorBatch is doing something else - can be used to fold multiple results into one).

**Comment by HolgerKnublauch** [comment]
Actually have you tried setting AbstractSPARQLExecutor.createDetails to true yet? It should produce sh:detail triples in the report. Please try that and get back to what is missing.

**Comment by umbreak** [comment]
This does provide more information. However there are few things to improve there:

1. It should be a flag on `ValidationEngineConfiguration`
2.  The report now is very verbose and duplicated (at least in the case I tested). Also the way `details` is embedded in the model seems wrong (very nested). Converting the report to JSON-LD (with the appropriate context) you can find out what I mean:
```json
{
  "@context": {
    "sh": "http://www.w3.org/ns/shacl#"
  },
  "@type": "sh:ValidationReport",
  "sh:conforms": false,
  "sh:result": {
    "@type": "sh:ValidationResult",
    "sh:detail": [
      {
        "@type": "sh:ValidationResult",
        "sh:detail": [
          {
            "@type": "sh:ValidationResult",
            "sh:detail": [
              {
                "@type": "sh:ValidationResult",
                "sh:focusNode": 1,
                "sh:resultMessage": "Value does not have datatype http://www.w3.org/2001/XMLSchema#anyURI",
                "sh:resultSeverity": "sh:Violation",
                "sh:sourceConstraintComponent": "sh:DatatypeConstraintComponent",
                "sh:sourceShape": "_:b13",
                "sh:value": 1
              },
              {
                "@type": "sh:ValidationResult",
                "sh:focusNode": 1,
                "sh:resultMessage": "Value does not have datatype http://www.w3.org/2001/XMLSchema#string",
                "sh:resultSeverity": "sh:Violation",
                "sh:sourceConstraintComponent": "sh:DatatypeConstraintComponent",
                "sh:sourceShape": "_:b11",
                "sh:value": 1
              }
            ],
            "sh:focusNode": "_:b9",
            "sh:resultMessage": "Value has none of the shapes from the 'or' list",
            "sh:resultPath": {
              "@id": "http://schema.org/unitCode"
            },
            "sh:resultSeverity": "sh:Violation",
            "sh:sourceConstraintComponent": "sh:OrConstraintComponent",
            "sh:sourceShape": "_:b15",
            "sh:value": 1
          }
        ],
        "sh:focusNode": "_:b9",
        "sh:resultMessage": "Value does not have shape http://localhost/v0/schemas/nexus/schemaorg/quantitativevalue/v0.1.0/shapes/QuantitativeValueShape",
        "sh:resultSeverity": "sh:Violation",
        "sh:sourceConstraintComponent": "sh:NodeConstraintComponent",
        "sh:sourceShape": "_:b10",
        "sh:value": "_:b9"
      }
    ],
    "sh:focusNode": "_:b9",
    "sh:resultSeverity": "sh:Violation",
    "sh:sourceConstraintComponent": "sh:AndConstraintComponent",
    "sh:sourceShape": "http://localhost/v0/schemas/nexus/core/quantitativevalue/v0.1.0/shapes/QuantitativeValueShape",
    "sh:value": "_:b9"
  }
}
```

**Comment by HolgerKnublauch** [comment]
I have just pushed a change that makes the reportDetails flag visible in the configuration object.

The report levels that you have copied look sensible to me. I don't see why it should drop the "intermediate" nodes as there is a nesting from sh:and to sh:node and finally sh:or. Each level adds some info (for some users, even if in your case you may not want this). If you prefer, you could just look at leaf violations, but that's your choice.

If that's acceptable, can this ticket be closed?

**Comment by umbreak** [comment]
I saw the commit. Seems good to me. Thanks again for the quick response.
From the point (2) you're right, It can be a client's choice to decide which results to present to the end user.
