### ISSUE TITLE
shacl Question

### ISSUE THREAD

**Issue by willemneal** [TopQuadrant/shacl#43]
I'm new to SHACL and trying use it to update an inferred value.

For example,
Data graph:
```turtle
:Doc a ex:Post.
:Reply ex:replyTo :Doc.
:Reply2 ex:replyTo :Doc.
```

Then have an inference which counts the number of replies and then inserts into the data the inferred value.

Is this possible with SHACL?

**Comment by HolgerKnublauch** [comment]
It is possible to express this inference, using a CONSTRUCT-based sh:rule or through a TripleRule that uses a user-defined SHACL function that computes the number of replies as an xsd:integer. All these features (from https://www.w3.org/TR/shacl-af/) are supported by the SHACL API.

However, to do these inferences automatically and incrementally as data changes is tricky. The first question you should ask is whether you really need this as an RDF triple. The alternative could be to just compute the values at query time, e.g. via a SPARQL function. This would ensure that the results are always up to date, and you save some memory for the inferred triples. If you really need them as a triple, you'd need to define some mechanism to trigger re-computation of the rules to replace previous inferences. SHACL API does not do this automatically.

FWIW I am right now working on an incremental approach to computing property values for the next SHACL API version, but it's not yet ready to be merged in. It will also not "materialize" inferences as triples though, just provide more elegant ways of computing certain properties dynamically.

Not sure if your question was more about the syntax on how to describe such inferences, or the API.

**Comment by willemneal** [comment]
Thanks for the response!   My question was regarding how it is possible with SHACL both is syntax and API.

The application that I am using this for is computing reputation which needs to update after a new review is added.  The new review updates the reputation of an article and thus the reputation of the article's author, which in turn effects the reputation of the article they have reviewed.  So when a new review is added it's effect should cascade and update all the corresponding reputations.  This could be done with querying but it would be preferred to just be a property.

One idea is that we can have a validation requirement that the number of reviews is equal to the pre-computed value.  This violation triggers the the Construct rule.

Essentially, I need updates to trigger all the inferred changes to the data since computing reputation over the graph each time seems like it would be too much, though your suggestion of elegant dynamic approach could work.

Also I'm very new to the RDF space and was wondering how SHACL and SHeX differ in terms of what I'm trying to accomplish.  From my understanding SHACL is a superset of Shex and SPIN, is this correct.

**Comment by irenetq** [comment]
SHACL is a W3C standard. ShEx and SPIN are not W3C standards.

Both SPIN and ShEx were member submissions to W3C that were used as inputs in development of SHACL. Quite a number of SPIN design points were taken up by SHACL. Thus, SHACL can be seen as SPIN 2.0. ShEx’s input to SHACL was only in terms of requirements.

In terms of what you are trying to do:

ShEx does not support rules and inferencing
SPIN does and you can use it to deliver your requirements, but it is not a standard and SHACL is, so we recommend using SHACL. 

Regards,

Irene

**Comment by lifan0127** [comment]
> FWIW I am right now working on an incremental approach to computing property values for the next SHACL API version, but it's not yet ready to be merged in. It will also not "materialize" inferences as triples though, just provide more elegant ways of computing certain properties dynamically.

Hello Holger, any update on the incremental inference feature you mentioned in your earlier response? Thanks~

**Comment by HolgerKnublauch** [comment]
This was referring to the support of sh:values that has been published for a while now, see

https://www.topquadrant.com/graphql/values.html
