### ISSUE TITLE
Q: SHACL constraints against SPARQL endpoints

### ISSUE THREAD

**Issue by fekaputra** [TopQuadrant/shacl#50]
Is it possible to run SHACL constraints validation against a SPARQL endpoint? 
I am currently working with a relatively large amount of data and it's quite troublesome to load it into memory (I am now using ValidationUtil). It would be very useful (and probably faster) if I can load the data into a triplestore and run SHACL validation against its endpoint.

**Comment by simonstey** [comment]
hi!

> Is it possible to run SHACL constraints validation against a SPARQL endpoint?

what do you want to validate? the data in the triplestore or only the data returned by the endpoint?

**Comment by fekaputra** [comment]
Hi Simon, it's the data in the triplestore; if I have data that is too large to fit in the memory, I will want to put this data in a triplestore and run my SHACL constraints on it.

**Comment by HolgerKnublauch** [comment]
The current implementation requires a Jena Graph to operate on. It doesn't just produce SPARQL queries that could then be sent to any end point - this would be an entirely different architecture. If you cannot wrap your triple store with a Jena Graph to do real-time querying, the only option I see would be to create a periodic clone of the data into, say, a Jena TDB and then do the validation on that.

**Comment by fekaputra** [comment]
Understood - thanks for the suggestions.
