### ISSUE TITLE
Only one pattern in list Constraint

### ISSUE THREAD

**Issue by DavideAllavena** [TopQuadrant/shacl#51]
I wish to express the concept that  just one pattern in a list should be present. 

This is a valid example graph:
```
@prefix ex: <http://example.com/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .

[
    a ex:ParentClass ;
    ex:property1 [ a ex:Class1 ];
] .
```

This is another valid example graph:
```
@prefix ex: <http://example.com/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .

[
    a ex:ParentClass ;
    ex:property2 [ a ex:Class2 ];
] .
```

This is the SHACL file:
```
@prefix ex: <http://example.com/> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .

ex:CatalogShape
    rdf:type sh:NodeShape ;
    sh:name "Class"@en ;
    sh:targetClass ex:ParentClass ;
    sh:property [
        sh:xone (
            [
                sh:path ex:property1 ;
                sh:class ex:Class1 ;
            ]
            [
                sh:path ex:property2 ;
                sh:class ex:Class2 ;
            ]
        );
        sh:minCount 1 ;
        sh:maxCount 1 ;
        sh:severity sh:Violation ;
    ]
.
```

This graph is considered valid but it is wrong:
```
@prefix ex: <http://example.com/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .

[
    a ex:ParentClass ;
    ex:property1 [ a ex:Class1 ];
    ex:property2 [ a ex:Class2 ];
] .
```

Is it a `shaclvalidate` issue or a SHACL file  problem?

**Comment by irenetq** [comment]
ex:CatalogShape
    rdf:type sh:NodeShape ;
    sh:name "Class"@en ;
    sh:targetClass ex:ParentClass ;
    sh:xone (
        [sh:property
               [sh:path ex:property1 ;
                sh:class ex:Class1 ;
		sh:minCount 1 ;
        	sh:maxCount 1 ;]
            ]
        [sh:property
               [sh:path ex:property2 ;
                sh:class ex:Class2 ;
		sh:minCount 1 ;
        	sh:maxCount 1 ;]
            ]
        );    
    
The value of sh:property must be a property shape. A property shape must be a subject of a triple that has sh:path as its predicate.

**Comment by DavideAllavena** [comment]
Thank you! That solved the Problem! I think we can close this issue.
