### ISSUE TITLE
Shack report result path

### ISSUE THREAD

**Issue by ienroll** [TopQuadrant/shacl#54]
Hi
 Can you provide an example to retrieve shacl validation report result path using Jena?

It appears it uses blank nodes and I am not able to retrieve RDF.first property statement using Resource. 

However I am able to retrieve other data like SH.result using blank node resource.

I think something is special about SH.resultpath value and I couldn’t figure out what it is. 
Any help is appreciated!

Thanks
Ravi

**Comment by HolgerKnublauch** [comment]
sh:resultPath is a copy of the required triples from the shapes graph. If you think some triples are missing, please provide a test scenario that I can run. Maybe you are in a different graph when you try to walk the path's triples? You need to query the results graph, not the shapes graph, and the blank nodes will have a different ID in both graphs.
