### ISSUE TITLE
migrate to RDF4J API

### ISSUE THREAD

**Issue by grexe** [TopQuadrant/shacl#55]
how much effort would it be to adopt RDF4J instead of Jena?
I would like to integrate the library into an existing project using RDF4J and am willing to take the plunge if needed and deemed feasible.

**Comment by afs** [comment]
[CommonsRDF](http://commons.apache.org/proper/commons-rdf/) provides a single API over a number of toolkits including Jena and RDF4J at the SPO level. It's good for writing algorithms over RDF - and could be suitable for the code deciding on the SPARQL queries.

**Comment by HolgerKnublauch** [comment]
We don't rely on Jena inferencing support. The only place where it's really used is in our support for sh:entailment, which is an optional feature for SHACL compliance.

**Comment by HolgerKnublauch** [comment]
The TopBraid SHACL API is for Jena, and no plans to change that. It is possible to bridge an RDF4J triple store with a Jena "facade", basically translating the Jena findSPO functions into corresponding RDF4J calls. Finally, with a link to http://docs.rdf4j.org/programming/#_validation_with_shacl allow me to close this ticket here.

**Comment by grexe** [comment]
Thanks @afs for the pointer to commonsrdf, but I see it's stale and adds another layer which adds complexity and may impact performance.
I like the facade approach @HolgerKnublauch suggested and will follow that approach, thanks to you both!

**Comment by grexe** [comment]
PS: I see that RDF4J 2.5 will officially add SHACL support in the docs you linked @HolgerKnublauch - from our experience, the SHACL support in RDF4J was quite limited so far, how do you see it stack up against this library?

**Comment by afs** [comment]
I think the word they ("commonsRDF") would prefer is "stable" - maybe you just forgot the "b" :-) .

It's a small so it's not going to change very often.

As a shim layer, the performance impact should be similar to a facade between systems.

**Comment by grexe** [comment]
thanks for the update @HolgerKnublauch, I'll have a closer look at your other suggestion then.
