### ISSUE TITLE
Return non-zero exit code in case of violations

### ISSUE THREAD

**Issue by p-conrad** [TopQuadrant/shacl#56]
Hello,

we are working on small a project showcasing the usage of Travis CI to automatically validate SHACL projects. We believe leveraging the CI can be beneficial to the development of SHACL ontologies by providing immediate feedback on faulty commits, preventing errors from propagating too far and therefore streamlining the development process. The final goal is to provide one single `.travis.yml` file anyone could add to their repository to get started quick and without any hassle.
In case you would like to take a look, current development progress can be found [here](https://github.com/p-conrad/shacl-ci-testing).
So far, we have managed to set up the testing environment and run validations on a small sample file ([example](https://travis-ci.com/p-conrad/shacl-ci-testing/builds/98077713)). However, having the build actually fail would require the validation util to return an exit code different from 0 in case any violations were encountered. Might I request such a modification? Of course, I could also try to implement this myself, in which case a little guidance on where to get started be much appreciated.

Thanks in advance!
Peter

**Comment by p-conrad** [comment]
I just went ahead and did the modification myself. It can be seen [here](https://github.com/p-conrad/shacl/commit/6c8aab4135b58d86ac8af2126d94de1e9b539391) but basically boils down to this:
```java
boolean conforms = report.getProperty(SH.conforms).getObject().asLiteral().getBoolean();
if (!conforms) {
	System.exit(1);
}
```
Using this modified version our builds now fail properly. I'm not sure if this is the proper way to do it, so may I ask for your opinion? In case you are fine with having this feature I would like to open a pull request later.

**Comment by HolgerKnublauch** [comment]
Yes this should make sense. I have applied a variation of your change (hopefully slightly more tolerant against unexpected values) here (among other commits):

https://github.com/TopQuadrant/shacl/commit/76257beb501381542361b52363329999363753ff

Please close if this addresses your issue.

**Comment by p-conrad** [comment]
Yes, this is perfect. Thank you!
