### ISSUE TITLE
XMLLiteral validation

### ISSUE THREAD

**Issue by derf-github** [TopQuadrant/shacl#57]
Hi,

Shacl doesn't produce an error when a property with the datatype XMLLiteral does not contain an XML value.

Here is a basic shape which defines the testProperty as an XMLLiteral datatype :
```
ex:TestShape
  rdf:type rdfs:Class ;
  rdf:type sh:NodeShape ;
  rdfs:label "Test shape" ;
  sh:property ex:TestShape-testProperty ;
.

ex:TestShape-testProperty
  sh:path ex:testProperty ;
  rdfs:label "Test property" ;
  sh:datatype rdf:XMLLiteral ;
.
```
**Working examples :**
The validation works as expected when trying to validate a malformed XML value.
```
ex:InvalidResource
  rdf:type ex:TestShape ;
  ex:testProperty "<p></m>"^^rdf:XMLLiteral ;
.
```
The above model produces the following report : 
```
[ a            sh:ValidationReport ;
  sh:conforms  false ;
  sh:result    [ a                             sh:ValidationResult ;
                 sh:focusNode                  ex:InvalidResource ;
                 sh:resultMessage              "Value does not have datatype http://www.w3.org/1999/02/22-rdf-syntax-ns#XMLLiteral" ;
                 sh:resultPath                 ex:testProperty ;
                 sh:resultSeverity             sh:Violation ;
                 sh:sourceConstraintComponent  sh:DatatypeConstraintComponent ;
                 sh:sourceShape                ex:TestShape-testProperty ;
                 sh:value                      "<p></m>"^^rdf:XMLLiteral
               ]
] .
```

The validation also works as expected when trying to validate a well-formed XML value.
```
ex:InvalidResource
  rdf:type ex:TestShape ;
  ex:testProperty "<p></p>"^^rdf:XMLLiteral ;
.
```

The above model produces the following report : 
```
[ a            sh:ValidationReport ;
  sh:conforms  true
] .
```
**Not working :** 
The following model contains a testProperty with a value which is not XML.

```
ex:InvalidResource
  rdf:type ex:TestShape ;
  ex:testProperty "Test"^^rdf:XMLLiteral ;
.
```
I would expect Shacl to raise a validation violation but here is the corresponding validation report : 

```
[ a            sh:ValidationReport ;
  sh:conforms  true
] .
```
Am I missing something?
Please find attached the complete version of the non-working example.
[example.zip](https://github.com/TopQuadrant/shacl/files/2795224/example.zip)

Thank you.

Fred.

**Comment by afs** [comment]
@derf-github, it might be a bit odd but `"Test"^^rdf:XMLLiteral` is valid. The lexical part must be valid self-contained XML content after it is put inside some start-end tags; the start-end tags don't have to be in the RDF literal. In other words, "no tags" fulfils the rule that tags are balanced.

https://www.w3.org/TR/rdf11-concepts/#section-XMLLiteral
