### ISSUE TITLE
Incorrect validation message for sh:in list

### ISSUE THREAD

**Issue by georgschmidtdumont** [TopQuadrant/shacl#58]
Given the following shape

```
test:EncodingConstraintShape
   a sh:NodeShape ;
   sh:targetClass test:EncodingConstraint ;
   sh:property [
      sh:path test:value ;
      sh:in ( test:US-ASCII test:ISO-8859-1 test:UTF-8 );
      sh:name "value" ;
      sh:description "Constrains the encoding (character set) of a property." ;
   ] .
```

in conjunction with the following RDF graph

```
:TestConstraint a test:EncodingConstraint ;
   test:value "UTF-8" .
```

I would expect a validation result similar to the following

```
[resultMessage:  Value is not in [test:US-ASCII, test:ISO-8859-1, test:UTF-8]
focusNode:      :TestConstraint
resultPath:     test:value
resultSeverity: http://www.w3.org/ns/shacl#Violation
value:          UTF-8
]
```

However I actually get a validation result similar to the following

```
[resultMessage:  Value is not in 7f6f0757-bbb2-4f17-9c16-188ecf75bb5e
focusNode:      :TestConstraint
resultPath:     test:value
resultSeverity: http://www.w3.org/ns/shacl#Violation
value:          UTF-8
]
```

I am using version 1.1.0.

**Comment by simonstey** [comment]
I suspect `7f6f0757-bbb2-4f17-9c16-188ecf75bb5e` is the bnode identifier of the list. 

as the SHACL specification does not impose any restrictions as to what result message needs to be returned, it's not incorrect https://www.w3.org/TR/shacl/#InConstraintComponent

br simon

**Comment by georgschmidtdumont** [comment]
Hi @simonstey 

I do share your assumption that `7f6f0757-bbb2-4f17-9c16-188ecf75bb5e` is the node identifier.

In version 1.0.1 the result message is returned as `Value is not in [test:US-ASCII, test:ISO-8859-1, test:UTF-8]`. Even if the specification does not impose any restrictions, IMHO the content of the result message should help the user identify the issue which in the current form is not the case.

regards,
Georg

**Comment by HolgerKnublauch** [comment]
Hi Georg, yes the current rendering is a bit geeky and not terribly useful for things like lists. You can control how such values are rendered via ValidationEngine.setLabelFunction. This flexibility is there because some people prefer qnames, while others prefer human-readable labels etc. If no such label function has been set, it will fall back to calling RDFLabels.get().getLabel (see SPARQLSubstitutions.withSubstitutions). Judging by what's on master now, this SHOULD gracefully handle rdf:Lists, however the implementation is probably expecting the rdf:List to be defined in the data graph, not in the shapes graph (and the sh:in is of course in the shapes graph).

Could you confirm: when the data graph imports the shapes graph, does the list render OK?

**Comment by georgschmidtdumont** [comment]
Hi @HolgerKnublauch,

adding the shapes graph to the data graph did not change the rendering of the list. However, creating a custom label function did fix the issue. Thanks for pointing me in the right direction!

**Comment by tfrancart** [comment]
Hello @georgschmidtdumont , this problem is common and if you could share your custom label function to print validation messages of `sh:in` this would help. Thanks !

**Comment by georgschmidtdumont** [comment]
Hi @tfrancart, I created a custom `ValidationEngineFactory` as follows:

```
public class CustomValidationEngineFactory extends ValidationEngineFactory {
   @Override
   public ValidationEngine create(final Dataset dataset, final URI shapesGraphURI, final ShapesGraph shapesGraph, final Resource report) {
      final ValidationEngine engine = super.create( dataset, shapesGraphURI, shapesGraph, report );
      engine.setLabelFunction( rdfNode -> RDFLabels.get().getNodeLabel( rdfNode ) );
      return engine;
   }
}
```

**Comment by tfrancart** [comment]
Thanks !

**Comment by HolgerKnublauch** [comment]
Does anyone see issues with this change, making the RDFLabels function the default?

https://github.com/TopQuadrant/shacl/commit/79b73a698270ab8793591e15f51ce310d625adc3
