### ISSUE TITLE
Distinguish between constraint with which all targets conforms, and constraints for which no targets were found

### ISSUE THREAD

**Issue by tfrancart** [TopQuadrant/shacl#6]
I would like to display a SHACL ValidationReport by breaking it down by Shapes and Constraints in the shapes graph. By doing so, I would like to be able to distinguish between the shapes that actually matched some targets in the data, and the targets all conforms with the shape, and the shapes that did not matched any targets. I think that there is currently no way of distinguishing the 2.
Thanks for making SHACL available.

**Comment by HolgerKnublauch** [comment]
We have nothing like this built-in right now. For TopBraid I would probably add a magic property to compute all target nodes for a given shape. Here, you'd currently need to write this (in SPARQL) yourself, e.g. loop over all sh:targetClass triples and check if there are instances of that class. Probably not prohibitively difficult as a work-around?
