### ISSUE TITLE
Get detailed explanations for Validation Results

### ISSUE THREAD

**Issue by kdrsslr** [TopQuadrant/shacl#60]
As per SHACL Specification **3.6.2.6 Details (sh:detail)** there exists a stack trace-like feature for Validation Results.
Is there currently a way to enable this feature in the ValidationEngine and if not, is it a planned feature?
Thanks in advance-

**Comment by HolgerKnublauch** [comment]
Have you tried ValidationEngine.setConfiguration using a config object with setReportDetails(true) ?

**Comment by kdrsslr** [comment]
Thanks for the hint! I haven't seen this option since I was looking locally in the source of 1.1.0 which does not contain this feature. I managed to find this [inofficial artifact](https://mvnrepository.com/artifact/org.topbraid/shacl/1.2.0-INTERNAL) to use it until it becomes available in the next official release.
