### ISSUE TITLE
Can we add label in sh:or and get violation information more specific to a label instead of sh:or failed. 

### ISSUE THREAD

**Issue by RammG** [TopQuadrant/shacl#63]

**Comment by RammG** [comment]
Right now, sh:or failed with information like failed sh:or validation, if we defined multiple sh:or in shape, it is difficult to know which part failed. Can we add label to sh:or and tell which part failed in validation?

**Comment by tfrancart** [comment]
I recently had exactly the same issue and found the "reportDetails" flag as described in #39 to be the answer. Basically it allows the "sub-issues" of an sh:or or sh:and validation to be included in the validation report as well.

**Comment by HolgerKnublauch** [comment]
Yes, if reportDetails addresses your need, can this ticket be closed?

**Comment by RammG** [comment]
yes, thanks.
