### ISSUE TITLE
RDF payload does not have anything defined in shape file should fail validation

### ISSUE THREAD

**Issue by RammG** [TopQuadrant/shacl#64]
If RDF payload which we apply shape validation for does not have anything defined in validation shape file, we should fail validation. Says you don't have any related thing to validate in your payload or similar information like that. Any concern for adding this constraint?

**Comment by tfrancart** [comment]
See also #38

**Comment by HolgerKnublauch** [comment]
Technically, if there are no shapes defined, then no violation should be produced. You can however add custom code as the one from Thomas as a pre-processing step.

**Comment by RammG** [comment]
kk
