### ISSUE TITLE
rdfs inference on the dataset

### ISSUE THREAD

**Issue by bertvannuffelen** [TopQuadrant/shacl#66]
Hi,

does this implementation implies per default rdfs inference?
So if my data contains 
 ```
   <a> a <C>.
   <C> rdfs:subClassOf <D>.
``` 

that a shape having as `sh:targetNode <D>` , applies to the `<a>`?

kr,

Bert

**Comment by simonstey** [comment]
Hi!
> does this implementation implies per default rdfs inference?

at least not full RDFS inferencing (per default), [which is in line with the standard](https://www.w3.org/TR/shacl/#shacl-rdfs):
<details>
<summary>1.5 Relationship between SHACL and RDFS inferencing</summary>

> SHACL uses the RDF and RDFS vocabularies, but full RDFS inferencing is not required.
>
>However, SHACL processors may operate on RDF graphs that include entailments [sparql11-entailment] - either pre-computed before being submitted to a SHACL processor or performed on the fly as part of SHACL processing (without modifying either data graph or shapes graph). To support processing of entailments, SHACL includes the property sh:entailment to indicate what inferencing is required by a given shapes graph.
>
>The values of the property sh:entailment are IRIs. Common values for this property are covered by [sparql11-entailment].

</details>
however, it applies all entailment regimes defined in your shapes graph:

https://github.com/TopQuadrant/shacl/blob/9f74a880acfd32f8735583798af896cd34075f83/src/main/java/org/topbraid/shacl/validation/ValidationUtil.java#L107-L118

where `applyEntailments()` is defined as:
https://github.com/TopQuadrant/shacl/blob/9f74a880acfd32f8735583798af896cd34075f83/src/main/java/org/topbraid/shacl/engine/AbstractEngine.java#L50-L62

-------------
> So if my data contains
> ```
> <a> a <C>.
>  <C> rdfs:subClassOf <D>.
> ```
>that a shape having as sh:targetNode <D> , applies to the <a>? 

you should use `sh:targetClass` for that.. cf. https://www.w3.org/TR/shacl/#targetClass

**Comment by bertvannuffelen** [comment]
Thanks for the swift reply.

I indeed found in the code back the proper handling of sh:entailment, according to the W3C standard.
Thanks for confirming that.

I was more wondering about the data. It looks like rdfs:subClassOf inference is applied, but I am not sure.
Your statement 
> at least not full RDFS inferencing 
leaves that in the middle.

Can you confirm whether it is applied or not?

**Comment by simonstey** [comment]
> I was more wondering about the data. It looks like rdfs:subClassOf inference is applied, but I am not sure.
> Your statement
> 
> > at least not full RDFS inferencing
> > leaves that in the middle.
> 
> Can you confirm whether it is applied or not?

when you use `sh:targetClass` (you used `sh:targetNode` in your example!) it _must_ be applied, because according to the standard https://www.w3.org/TR/shacl/#targetClass:
> Note that, according to the SHACL instance definition, all the rdfs:subClassOf declarations needed to walk the class hierarchy need to exist in the data graph.

**Comment by bertvannuffelen** [comment]
Ok I see it, but then -- more as a critique on the standard -- I would have made that far more clearer.

In the intro, on data graphs:

> 

> SHACL makes no assumptions about whether a graph contains triples that are entailed from the graph under any RDF entailment regime.
> 
> The data graph is expected to include all the ontology axioms related to the data and especially all the rdfs:subClassOf triples in order for SHACL to correctly identify class targets and validate Core SHACL constraints. 
 
I would have added something like: SHACL will evaluate against the data obtained by closure of the data graph under rdfs:subclassOf .

thanks for the pointers and feedback.

**Comment by HolgerKnublauch** [comment]
Yeah, the spec is not meant to be a tutorial so it's very brief in places. I presume I can close this ticket for now though.
