### ISSUE TITLE
shaclvalidate.sh SLF4J error

### ISSUE THREAD

**Issue by RichardWallis** [TopQuadrant/shacl#69]
Running shacl-1.2.0
The following appears in the output:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```
This is referenced on the [SLF4J site ](https://www.slf4j.org/codes.html#StaticLoggerBinder) which recommends:
> Placing one (and only one) of slf4j-nop.jar slf4j-simple.jar, slf4j-log4j12.jar, slf4j-jdk14.jar or logback-classic.jar on the class path should solve the problem. 

I have locally tested it with the relevant version of slf4j-nop.jar (```slf4j-nop-1.7.26.jar```) and it solves the problem.

I am running it in a cloud based environment so doing the patch every time a download of the API occurs is not ideal. 

Plus, as there is version dependancy with the main slf4j-api-1.7.26.jar, can these be bundled together in future ships.

**Comment by HolgerKnublauch** [comment]
Hi Richard, I cannot add a dependency on this for SHACL API as a library, yet I agree the current solution for command line is not good. I am not a Maven expert and cannot right now afford to spend much time on figuring out a solution that would inject the nop.jar file into the binary build while not affecting API users. I welcome contributions/pull requests.

**Comment by acoburn** [comment]
I am very interested in using this code as a library (and hence do not want a particular logging implementation added as a dependency), but I agree that it would be useful to have one available for the binary build.

One possibility would be to do a little re-organizing of the code base, moving everything that is currently in `./src` into what would be a maven submodule (e.g. `./shacl/src`). Separately, you could create a new maven submodule: `./cli`, which has a dependency on the `shacl` code plus a dependency on some particular logging implementation (e.g. logback or log4j). The shell scripts that currently run this code would be relocated to that second module.

I would be happy to do this work, but it will involve a lot of moving files around. @HolgerKnublauch if you like that approach, I can supply a PR.

**Comment by HolgerKnublauch** [comment]
Talking to a colleague I got the same impression, that this may require a different module structure with different pom files. That's why I shied away from the busyness. He also gave me this suggestion, which I did not investigate: "Maybe there is a way to use assembly dependencySets with scope=test (and not optional=true) would work."

But yes, whatever works would be appreciated.

**Comment by HolgerKnublauch** [comment]
This morning I noticed that there might be a much simpler work-around to address the useless output to system.err: If I modify the main functions of Validate and Infer along the lines of
	
	public static void main(String[] args) throws IOException {
		// Temporarily redirect system.err to avoid SLF4J warning
		System.err.println("Hello");
		PrintStream oldPS = System.err;
		System.setErr(new PrintStream(new ByteArrayOutputStream()));
		Validate validate = new Validate();
		System.setErr(oldPS);
		validate.run(args);
	}

In that case I no longer see the warning, yet other (real) errors will be printed as before.

Does anyone see a problem with this? To me this would be greatly preferred over the much larger refactoring that would impact how the project gets deployed and published to maven central etc.

**Comment by HolgerKnublauch** [comment]
I have meanwhile applied the suggested work-around to master, and it would go live with the next official release. It would be good to have some 3rd party confirmation that this addresses the problem. (And apologies, acoburn if this made your PR and time spent on it unnecessary).

**Comment by acoburn** [comment]
@HolgerKnublauch no worries, that PR didn't actually take much time.
