### ISSUE TITLE
shaclvalidate.sh output 

### ISSUE THREAD

**Issue by RichardWallis** [TopQuadrant/shacl#70]
Whilst identifying the logging error in shaclvalidate.sh - issue (#69) - I was trying to capture the report output separate from the error logging.

When there are no errors it is simple:
```shaclvalidate.sh -datafile testdat1.ttl -shapesfile testshapes.ttl  > reportfile```

It would have been more convenient, and potentially useful, if the output file could be specified:
```shaclvalidate.sh -datafile testdat1.ttl -shapesfile testshapes.ttl -output reportfile```

Just a suggestion ...

**Comment by namedgraph** [comment]
@RichardWallis assuming that the error log is printed to `stderr`, you can redirect it separately from `stdout` using shell: https://askubuntu.com/questions/625224/how-to-redirect-stderr-to-a-file

**Comment by HolgerKnublauch** [comment]
I would also say that fixing #69 should be better than adding more infrastructure to work around the issue. Can this ticket here be closed?
