### ISSUE TITLE
API Design question

### ISSUE THREAD

**Issue by Locke** [TopQuadrant/shacl#72]
I recently worked on the [SHACL Protégé Plugin](https://github.com/fekaputra/shacl-plugin/) to bring it up to date and to support some essential features.

Thereby I wrote two high level classes to work with the validation results from this library - instead of working in the UI directly with the plain Jena Model from `ValidationUtil.validateModel`:

- https://github.com/fekaputra/shacl-plugin/blob/master/src/main/java/at/ac/tuwien/shacl/plugin/util/ShaclValidationReport.java
- https://github.com/fekaputra/shacl-plugin/blob/master/src/main/java/at/ac/tuwien/shacl/plugin/util/ShaclValidationResult.java

The Protégé plugin uses the `ShaclValidationReport` class to create a table that is sorted and can be filtered:

<img width="646" alt="protege-shacl-plugin" src="https://user-images.githubusercontent.com/53905/61941146-3673ec00-af97-11e9-917a-e44ccfee5d5c.png">

For a code / usage example, the validation results are filtered here: https://github.com/fekaputra/shacl-plugin/blob/master/src/main/java/at/ac/tuwien/shacl/plugin/ui/ShaclConstraintViolationPanel.java#L147

I now want to use this SHACL API library in another / completely new project and again, I need some abstraction over the plain Jena Model that `ValidationUtil.validateModel` returns.

Now to my actual questions:

Have I missed something from this library, or are you really only providing a Jena Model as result?

Would you be interested in providing some kind of abstraction for the validation results in this library complementary to the Jena Model, i.e. do you think it would it make sense, for example, to import my two classes and provide / maintain them with this library?
I think the current implementation of `ShaclValidationResult.compareTo` needs to be generalized more or even be removed / to be provided by the library users. Besides that, I hope I haven't missed anything and that my two classes cover everything from the validation results.

If you're not interested, I will probably create and maintain a small library just for these two files, however I fear that's a lot of overhead..

From a license perspective, I believe the MIT license used in the Protégé Plugin allows usage here under the Apache 2.0 License. If not, as I am the only author, I hereby grant you usage of the two classes `ShaclValidationReport` and `ShaclValidationResult` in this project.

**Comment by tfrancart** [comment]
Would be definitely useful to have this, as I already had to code this kind of object-modeling of the validation result 2 or 3 times.
Warning though, I think one can define custom Severities for the Shapes (?), you probably don't want this as an enum.

**Comment by Locke** [comment]
> Warning though, I think one can define custom Severities for the Shapes (?), you probably don't want this as an enum.

Thanks, you are right and I missed that. In the informative part of https://www.w3.org/TR/shacl/#severity this is even mentioned:
> Any IRI can be used as a severity.

**Comment by HolgerKnublauch** [comment]
I have been asking myself the same question. One approach would be if the SHACL API would directly only produce such Java objects, and the RDF graph gets produced as an (optional) second step. This might improve performance a bit.

**Comment by HolgerKnublauch** [comment]
I have added such a convenience layer, see https://github.com/TopQuadrant/shacl/commit/0e7ae85503c66e3421268c32afa1ce0ea7f2db33

Could you check if that does what you wanted?

**Comment by Locke** [comment]
I migrated from my `ShaclValidationResult` to your `ValidationResult` in [9dc1e0b](https://github.com/Locke/shacl-plugin/commit/9dc1e0b06454841728b51299a0f91f9ab43faf56). It was basically straightforward and seems to work very fine.


A general design flavor of mine is to wrap the `List<ValidationResult>` with a simple custom object, like I do with [ShaclValidationReport.java](https://github.com/Locke/shacl-plugin/blob/9dc1e0b06454841728b51299a0f91f9ab43faf56/src/main/java/at/ac/tuwien/shacl/plugin/util/ShaclValidationReport). In my opinion this makes the code more readable than just a `List<ValidationResult>`, especially when it is passed around as argument or even by an Observable, and also as type erasure would make this just a `List<>` that cannot be distinguished from any other List at runtime. Additionally, this might make future extensions / implementation changes easier.


As I call `ValidationUtil.validateModel`, which internally creates a temporary `ValidationEngine`, I cannot access `ValidationEngine.getValidationResults` and currently have to recreate its behavior for now [manually here](https://github.com/Locke/shacl-plugin/blob/9dc1e0b06454841728b51299a0f91f9ab43faf56/src/main/java/at/ac/tuwien/shacl/plugin/util/ShaclValidationReport.java#L22). The mapping should be exposed from a `ValidationUtil` method.


Thereby: instead of adding the ValidationResults manually to a LinkedList in `ValidationEngine.getValidationResults` I suggest to use `mapWith` like on other locations:

```
public List<ValidationResult> getValidationResults() {
    return report.listProperties(SH.result).mapWith(s -> (ValidationResult) new ResourceValidationResult(s.getResource())).toList();
}
```

The cast is necessary as otherwise the result would be `List<ResourceValidationResult>`.





Furthermore, I am really not sure about this yet, it might be useful to override `equals` and `hashCode`, so that `ResourceValidationResult` can be safely used in a `Set` instead of a `List`:

```
@Override
public boolean equals(Object o) {
    if (this == o) return true;
    return (o instanceof ResourceValidationResult)
            && result.equals(((ResourceValidationResult) o).result);
}

@Override
public int hashCode() {
    return Objects.hash(result);
}
```

However, if you expect more implementations of `ValidationResult`, the `equals` method might should compare all fields via the interface getters to be comparable with any implementation...

**Comment by HolgerKnublauch** [comment]
I have added ValidationReport and equals/hashCode as suggested.

On ValidationUtil, I added a comment to explain my thinking. It would cause a duplication of utility functions for the various parameters and result types. Also, most users may want to take more control over the shapes graph creation than going through the util methods.

**Comment by HolgerKnublauch** [comment]
(In the absence of further util functions, just create an instance of ResourceValidationReport directly using the result Resource as input.

**Comment by Locke** [comment]
Thank you very much for all the work! This now looks exactly as I need it.

I will stick to the util method and `new ResourceValidationReport(Resource report)` for now.

I'm curious: is there any particular reason in ResourceValidationReport why you are manually adding the results to an ArrayList, instead of my suggestion like below?

```java
public ResourceValidationReport(Resource report) {
	this.report = report;
	this.results = report.listProperties(SH.result).mapWith(s -> (ValidationResult) new ResourceValidationResult(s.getResource())).toList();
}
```

**Comment by HolgerKnublauch** [comment]
I am glad I could help and thanks for your suggestions. The difference between the styles is quite random, no strong opinion.
