### ISSUE TITLE
Release 1.2.0 is broken, because of missing antlr-shaded

### ISSUE THREAD

**Issue by KMax** [TopQuadrant/shacl#73]
Tried to upgrade from the 1.1.0 version up to 1.2.0, but Gradle wasn't able to resolve a dependency:

```
Could not determine the dependencies of task ':model-generator:jar'.
> Could not resolve all files for configuration ':model-generator:compileClasspath'.
   > Could not find org.topbraid:antlr-shaded:4.5.3.
     Searched in the following locations:
       - file:/home/kolchinmax/.m2/repository/org/topbraid/antlr-shaded/4.5.3/antlr-shaded-4.5.3.pom
       - file:/home/kolchinmax/.m2/repository/org/topbraid/antlr-shaded/4.5.3/antlr-shaded-4.5.3.jar
       - https://repo.maven.apache.org/maven2/org/topbraid/antlr-shaded/4.5.3/antlr-shaded-4.5.3.pom
       - https://repo.maven.apache.org/maven2/org/topbraid/antlr-shaded/4.5.3/antlr-shaded-4.5.3.jar
     Required by:
         project :model-generator > org.topbraid:shacl:1.2.0
```

I guess the cause is that `org.topbraid:antlr-shaded:4.5.3` is expected to be manually placed in a specific directory. A fragment of the pom.xml of shacl:1.2.0:

```
<repositories>
    <repository>
      <id>org.topbraid.antlr</id>
      <url>file://${basedir}/lib</url>
    </repository>
  </repositories>
```

**Comment by HolgerKnublauch** [comment]
This is weird. I am sure I had tested this after it went live, but maybe I still had files cached in my local maven repo, so it worked for me. But I can confirm this build doesn't work!

I'll see if I can get a new 1.2.1 release done today - the current master branch already no longer has the antlr shaded reference thanks to a PR from Andy. I do have other changes to put onto master too.

**Comment by HolgerKnublauch** [comment]
Version 1.2.1 has been released. Please try again if you get a chance and let me know if it works for you.

**Comment by KMax** [comment]
Yes, now it works fine. Thank you for a quick fix!
