### ISSUE TITLE
Extend model with SHPath

### ISSUE THREAD

**Issue by tfrancart** [TopQuadrant/shacl#78]
I'd like to contribute by extending the model package with SHPath (from previous work on [ELI validator](https://webgate.ec.europa.eu/eli-validator/)). Here is basically what I had :

```
public interface Path {

	enum PathConstruct {
		PREDICATE_PATH,
		INVERSE_PATH,
		SEQUENCE_PATH,
		ALTERNATIVE_PATH,
		ZEROORMORE_PATH,
		ONEORMORE_PATH,
		ZEROORONE_PATH
	}
	
	/**
	 * The type of this path
	 * @return
	 */
	public PathConstruct getPathConstruct();
	
	/**
	 * Returns the predicate for a PredicatePath, InversePath, ZeroOrMorePath, OneOrMorePath, ZeroOrOnePath
	 * @return
	 */
	public Resource getPredicate();
	
	/**
	 * Returns the subpaths for SequencePath, AlternativePath
	 * @return
	 */
	public List<Path> getSubPaths();
	
}
```

Questions :
  - Interested ?
  - Is it OK like that or hhould there rather be Java subclasses corresponding to the different types of path, rather than the PathConstruct property ? in that case, how can the proper type of path be associated to the Java class in the SHFactory ?
  - in SHPropertShape, should `getPredicate` still return null in case the predicate is a path, and a different method is added to fetch the path ? (probably safest solution), or should the return type of `getPredicate`be changed to SHPath ?

Cheers
Thomas

**Comment by HolgerKnublauch** [comment]
Right. It sounds like a sensible thing. So far I have mostly operated on Jena Path objects directly, created with something like

jenaPath = (Path) SHACLPaths.getJenaPath(SHACLPaths.getPathString(path), path.getModel());

But a Model API layout would help traversing those paths.

My personal preference would be to define subclasses, but an enum would work too. A factory function could be SHFactory.asPath(r) and then SHPropertyShape.getPath()

As the term Path is overloaded already in many places, I'd suggest SHPath as the base interface

**Comment by tfrancart** [comment]
> My personal preference would be to define subclasses

OK, but I need a little help then : as SHFactory currently uses SimpleImplementation, itself deriving from ImplementationByType that checks that the resource has the proper type, and that elements from SHACL Paths don't have an rdf:type, how should the factory code should look like to create all these subclasses of Path ?

Thanks

**Comment by HolgerKnublauch** [comment]
I think we'd need to decide whether SHPath should be a subclass/interface of Resource at all. Arguably it doesn't really need to. For example otherwise normal URI resources kind-of overlap with named property paths. Do you need them to be subclass of Resource?

**Comment by tfrancart** [comment]
> Do you need them to be subclass of Resource?

What I would like to do is to be able to read a Model either as a plain Model (and send SPARQL queries or navigate the graph using plain Jena API), or by using vocabulary-specific views on some of the resources. I liked the idea that both point-of-views can coexist on the nodes in the graph. Same idea with the ValidationReport.
I think what I really _need_ is the ability to construct an SHPath from a Resource; whether the SHPath is a subclass of resource is secondary I think.
I leave the final word to you.

**Comment by HolgerKnublauch** [comment]
I cannot "own" this feature as I am basically booked out until next year. You are welcome to contribute a PR. I think as long as there is a .getResource() or .asResource() function in those path objects, they don't need to subclass Resource.

**Comment by HolgerKnublauch** [comment]
Closing old ticket
