### ISSUE TITLE
SHACL compact writer does not output valid syntax.

### ISSUE THREAD

**Issue by afs** [TopQuadrant/shacl#80]
shape ex:PersonShape -> ex:Person {}

is written 

    ex:PersonShape -> ex:Person {
    }

which does not parse.

    line 1:36 extraneous input 'ex:PersonShape' expecting {<EOF>, 'BASE', 'IMPORTS', 'PREFIX', 'shapeClass', 'shape'}

**Comment by HolgerKnublauch** [comment]
Thanks, merged.
