### ISSUE TITLE
TripleRule referencing multiple values generates only 1 inference

### ISSUE THREAD

**Issue by michaelcpuckett** [TopQuadrant/shacl#85]
When using a sh:TripleRule and the subject is a NodeShape with a path that refers to a property with multiple values, only the first value is chosen.

Is this the intended behavior? If so, is there a way to explicitly select all values instead of just the first one, or dynamically generate a TripleRule for each?

I'm using shaclinfer.bat or shaclvalidate.bat on the following:

Shapes:

```ttl
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix schema: <http://schema.org/> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

 [
    a sh:NodeShape;
    rdfs:isDefinedBy [
      a owl:Ontology;
      sh:entailment sh:Rules
    ];
    sh:property [
      sh:class schema:Article;
      sh:minCount 2;
      sh:path <http://news.example/vocab/articles>
    ];
    sh:rule [
      a sh:TripleRule;
      sh:object schema:Article;
      sh:predicate rdf:type;
      sh:subject [sh:path <http://news.example/vocab/articles>]
    ];
    sh:targetClass <http://news.example/vocab/Response>
  ] .
```

Data:

```ttl
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix news: <http://news.example/vocab/> .

 [
    a news:Response;
    news:articles [
      news:author "Alice Jones";
      news:headline "Example headline 1"
    ], [
      news:author "John Doe";
      news:headline "Example headline 2"
    ]
  ] .
```

**Comment by HolgerKnublauch** [comment]
Many thanks for this report, Michael. This was a bug indeed. It only ever walked subjects and predicates once. The error went unnoticed because (I guess) in all of my previous use cases only the object was iterated over. A fix is here:

https://github.com/TopQuadrant/shacl/commit/cf7c0d5c8dcee5a5ec8f591a4f97cdf7fd008c2e

**Comment by HolgerKnublauch** [comment]
Meanwhile, if you need a work-around for this scenario, try defining the rule directly on the articles, e.g. with sh:targetObjectsOf news:articles and then use sh:subject sh:this.

If you could confirm the fix we can hopefully close this ticket.

**Comment by michaelcpuckett** [comment]
@HolgerKnublauch Yes, I was able to build with the fix and everything works as expected. Thank you!
