### ISSUE TITLE
Dead link for binary distribution

### ISSUE THREAD

**Issue by NeilGraham** [TopQuadrant/shacl#86]
Link for the binary distributions in the README.md seems to be dead.
```
http://central.maven.org/maven2/org/topbraid/shacl/
```

**Comment by HolgerKnublauch** [comment]
http://central.maven.org is down for me too. I guess that's a temporary glitch?

**Comment by nextcen-dgemoets** [comment]
Depending on exactly what you want to link to, you could link to https://mvnrepository.com/artifact/org.topbraid/shacl or https://repo.maven.apache.org/maven2/org/topbraid/shacl/ instead.

**Comment by afs** [comment]
central.maven.org no longer has a DNS entry.

Use https://repo.maven.org/  NB the https.

This is a general issue. They have switched to https (part of the general trend to https I guess) and the certificate is for "repo". 

"repo1" also works. 

For a while, "http://central" went to repo1 failed on bad certificate. The DNS entry has gone for a while now.

**Comment by HolgerKnublauch** [comment]
Thanks, Andy. I did try repo.maven.org but also got an error, yet thankfully repo1 seems to be working fine.
