### ISSUE TITLE
Broken link in Dash ontology

### ISSUE THREAD

**Issue by gaurav** [TopQuadrant/shacl#87]
The Dash ontology imports Tosh as an import:

https://github.com/TopQuadrant/shacl/blob/80b069a9f1275f1f67c3143701f1868fd3525694/src/main/resources/rdf/dash.ttl#L20

However, it is not available at that URL: http://topbraid.org/tosh

Just making a note of this so it can be corrected! It might be referenced from somewhere else as well; I've tried to load the Tosh ontology before the Dash ontology, but I still get a 404 Not Found exception from `o.a.jena.ontology.OntDocumentManager`.

**Comment by HolgerKnublauch** [comment]
Thanks for pointing this out. I have uploaded the tosh files to that URL.
