### ISSUE TITLE
SH class does not declare SH.stem and SH.pattern, while these components are properly checked

### ISSUE THREAD

**Issue by tfrancart** [TopQuadrant/shacl#9]

**Comment by tfrancart** [comment]
And also these are missing I think :

SH.minLength,
SH.maxLength,
SH.pattern,
SH.stem,
SH.uniqueLang
SH.equals,
SH.disjoint,
SH.lessThan,
SH.lessThanOrEquals,

**Comment by HolgerKnublauch** [comment]
Thanks I have fixed that on my local copy, and these changes will be copied over to the GitHub version with the next update. Note that the WG has yesterday decided to drop sh:stem - we are trying to get rid of non-essential ballast to save time. I plan to move sh:stem into dash:stem.

**Comment by tfrancart** [comment]
Thanks. sh:stem was useful to check if a value from a certain property belongs to a given vocabulary/thesauri, just by looking at the beginning of its URI; but I understand the decision to drop it from the core if this eases the path to recommendation. Moving stem in dash:stem means that I could still use dash:stem where I was using sh:stem to achieve the same result ?

**Comment by HolgerKnublauch** [comment]
Yes dash:stem is identical to sh:stem.
