### ISSUE TITLE
Feature request: use namespace declarations from input in output

### ISSUE THREAD

**Issue by fkleedorfer** [TopQuadrant/shacl#95]
When using the commandline tool you provide for checking and inferencing, I would have a much easier time reading the output (especially, the triples generated by the rules), if the namespace declarations from the input files were used in the output as well. 

Cheers!

**Comment by HolgerKnublauch** [comment]
Judging by the source code it's using the prefixes from the data graph. Are you saying that your files have the prefix declarations in the shapes graph only?

**Comment by fkleedorfer** [comment]
The output of `shaclvalidate` has all the prefixes from the datafile. It would not hurt if the sh: prefix was also declared in the validation report for better readability.

The output of `shaclinfer` only has
 
```
@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix owl:   <http://www.w3.org/2002/07/owl#> .
@prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
```
independently of prefix declaration in shape or data files.

**Comment by HolgerKnublauch** [comment]
Could you verify that it's better now?

**Comment by fkleedorfer** [comment]
Yes it is. Many thanks!
