### ISSUE TITLE
SPARQL-based constraints not evaluated inside sh:and 

### ISSUE THREAD

**Issue by fkleedorfer** [TopQuadrant/shacl#96]
For this data graph:
```
@prefix ex:<https://example.com/ns#> .
@prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
@prefix sh:    <http://www.w3.org/ns/shacl#> .
@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .

ex:
    sh:declare [
        sh:prefix "ex" ;
        sh:namespace "https://example.com/ns#" ;
    ] .

ex:a 
    a                   ex:Example ;
    ex:minimal          false ;
    ex:selfContained    true 
    .
```
The following shape does what is expected (one validation result):
```
ex:revealAndBug 
    a                   sh:NodeShape ;
    sh:targetClass      ex:Example  ;
    sh:property [
        sh:path     ex:selfContained ;
        sh:hasValue true ;
    ]  ;
    sh:sparql [
        sh:prefixes ex: ;
        sh:message "Example is not minimal" ;
        sh:select """
            SELECT ?this 
            WHERE {
                ?this ex:minimal false .
            }
        """ 
    ] .
```

However, if you put the property shape and the sparql constraint shape in a `sh:and`, leaving everything else the same:
```
ex:revealAndBug 
    a                   sh:NodeShape ;
    sh:targetClass      ex:Example  ;
    sh:and (
        sh:property [
            sh:path     ex:selfContained ;
            sh:hasValue true ;
        ]  
        sh:sparql [
            sh:prefixes ex: ;
            sh:message "Example is not minimal" ;
            sh:select """
                SELECT ?this 
                WHERE {
                    ?this ex:minimal false .
                }
            """ 
        ] 
    ) .
```
The validation results disappear, the data graph conforms. Playing around with the SPARQL query shows that it doesn't even get parsed: replace the query with
```
            sh:select """
                THIS IS INVALID SPARQL!
            """ 
```
And still, there are no validation results - the graph conforms.

**Comment by HolgerKnublauch** [comment]
I think it's a Turtle syntax issue. sh:and takes a list of (node) shapes as value. Each member would need to be its own blank node, e.g.

sh:and ( 
    [ 
        sh:property [ ... ]
    ]
    [
        sh:sparql [ ... ]
    ]
)

Having said this, sh:and is reduntant as you could just as well attach the sh:property shape and the sh:sparql constraint to the parent (ex:revealAndBug). Defining multiple constraints at a shape means an implicit 'and'.

**Comment by fkleedorfer** [comment]
Thanks! Can I make this a feature request for a parser warning about the somehow bogus sh:and construct not containing any node shapes, then?
