### ISSUE TITLE
List Rules?

### ISSUE THREAD

**Issue by fkleedorfer** [TopQuadrant/shacl#97]
I am trying to do something a bit weird: generate SHACL Shapes using SHACL-AF Rules. As it's just RDF, that should work nicely, I thought, and it does. However, there is one issue I don't get around: I can't produce RDF lists (ie., RDF Collections using `rdf:first`/`rdf:rest`) with SPARQLRules (or triple RULES), such that each list item is from one solution of the query (as you'd do it with `GROUP_CONCAT`). [I don't think that SPARQL allows you to do that](https://stackoverflow.com/questions/62030465/sparql-construct-to-generate-rdf-collection-from-group-by-bindings).  Lists are all over the place in SHACL, so that's a serious limit to what you can do. (Right now I would like to generate a `sh:or` with one property shape per query solution, btw.)

However, if we were to define a new Rule type, 'List Rules', the list creation could be done by the SHACL processor. Just like a `sh:TripleRule`, with `sh:subject` and `sh:predicate`, but instead of `sh:object`, there's a `sh:listObject`, which must be a SHACL Node Expression, and the result is the cross product of all subject/predicate combinations and in the object position we could put the the nodes resulting from the list expression, transformed into an RDF list. 

Of course I could be mistaken, and it's perfectly possible to generate RDF lists using SHACL-AF Rules, in that case, I'd be thankful for a hint as to how... but otherwise - is that something you'd consider?

**Comment by fkleedorfer** [comment]
Maybe rather, `dash:listObject`, not `sh:listObject`

**Comment by fkleedorfer** [comment]
Of course, the List Rules only work for generating `sh:or` shapes if the shapes in the list are IRIs, not blank nodes, because there is no way to generate a blank node such that it can be referenced in the list, I believe. 

Not sure if the following is all that would be needed, but at least half a solution is to allow nesting for `sh:TripleRule`s. For nested triple rules that are linked to a triple rule shape using, say `dash:nestedTripleRule`, we could define that the child rule has access to the parent's subject, predicate, and object node sets, e.g. via `[ sh:path ( [ sh:inversePath  dash:nestedTripleRule ] sh:object ) ]`, and that way, you should be able to create any blank node structure needed.

**Comment by HolgerKnublauch** [comment]
I think SPARQL is not the best technology for creating rdf:Lists. It would require recursion for that, at least. In our system, we ended up defining a magic property (for Jena) that would produce all triples needed as bindings for ?s ?p ?o and then CONSTRUCT/INSERT becomes possible.

I don't think not enough use cases really require using rdf:Lists, so although I can sympathize with your suffering w.r.t. sh:in I don't think this is worth putting new substantial features into SHACL or DASH.

**Comment by fkleedorfer** [comment]
That's sad to hear... but I agree on the limited use cases: ironically, other than generating SHACL, I cannot think of one.  
I am trying to get there with JavaScript Rules, but it seems to be a bit tedious. Other than that, the best option seems to be to use jena magic properties, thanks for that hint! Using that would mean our shapes lose portability but I guess that's acceptable for us, so that's probably what I'm going to do. I was kind of hoping to find the PropertyFunction for generating the list bindings you mentioned in the TopQuadrant/shacl codebase, but it must be in another project. Sounds like it would be a useful contribution to the ARQ property function library, too ;-)

**Comment by HolgerKnublauch** [comment]
Right, the property function that we had for rdf:Lists is in our private code base, and it's pretty specialized too.

With this, I suggest we close this ticket if you don't mind.

**Comment by fkleedorfer** [comment]
Yes of course - many thanks for your help!!
