### ISSUE TITLE
make shaclc->shacl nearly lossless

### ISSUE THREAD

**Issue by VladimirAlexiev** [TopQuadrant/shacl#98]
@HolgerKnublauch wrote in #91:
- The prefixes are empty because your code just uses new PrefixMapStd() which is empty I guess.
- the SHACLC writer is really just a toy and will not work for many if not most real SHACL files... Once you convert shapes to SHACLC you'll possibly lose triples because SHACL is much richer than that.

Holger wrote "I regard the Compact Syntax as a decent way of getting definitions INTO a system, but not as an output format". However, SHACLC is much nicer to edit, so we (Onto) should fix the basic bugs, and should expand the SHACLC writer to cover as many cases as reasonable.

@yasengmarinov made a command-line tool `shaclconvert` that we should merge here. 

@rdstn is working on SHACL generation from Ontotext Platform schemas, and we want to output both SHACL and SHACLC. Our schemas omit some "exotic" SHACL features like `not` and `xone`, and make limited use of `or`, so I think that's feasible.

I now have the hang of editing the spec https://w3c.github.io/shacl/shacl-compact-syntax/, so I could add bits to SHACLC if needed.

**Comment by VladimirAlexiev** [comment]
I use the command-line tool also as a validator in emacs (and define a mode based on SHEX to get syntax highlighting):
```elisp
(define-derived-mode SHACLC-mode shexc-mode "SHACLC")
(add-to-list 'auto-mode-alist '("\\.shaclc$" . SHACLC-mode)) ; TODO: use the grammar to make highlighting better

;; https://gitlab.ontotext.com/yasen.marinov/shaclconvert.
;; Not part of TQ SHACL but I've put it in the same folder
(flycheck-define-checker shaclc-shaclconvert
  "SHACLC syntax checker using shaclconvert"
  :command ("java" "-jar" "c:\\prog\\shacl-1.3.2\\bin\\shaclconvert.jar" source "c:\\tmp\\INGORE.shacl")
  :error-patterns
  ((error "line " line ":" column " " (message))
   (error "Exception in thread \"main\" java.lang.RuntimeException: " (message)))
  :modes (SHACLC-mode))
(add-to-list 'flycheck-checkers 'shaclc-shaclconvert)
```

It helps writing shapes immensely!
![image](https://user-images.githubusercontent.com/536250/84401363-dbc59c00-ac0b-11ea-86f4-6a0d02b779b2.png)

SHACLC shapes are a lot more readable than SHACL:
![image](https://user-images.githubusercontent.com/536250/84401421-eda73f00-ac0b-11ea-99b7-a3e2ac0388f1.png)

**Comment by VladimirAlexiev** [comment]
@HolgerKnublauch , can you assign this to @rdstn ?

**Comment by HolgerKnublauch** [comment]
I don't see @rdstn in any list here. Maybe he/she needs to make a commit or PR first? In any case, I guess it's a formality as long as you guys know what to work on.

**Comment by HolgerKnublauch** [comment]
Have you thought about some extension fallback mechanism so that SHC files could express basically *all* SHACL files? What I am thinking about is: the SHACL-to-SHC exporter first prints all shapes in the nice compact syntax, and ticks off any triples that are "consumed" now. All remaining triples go into a block at the end, e.g. in Turtle.

This would mean that users can start writing their shapes in Compact syntax and then, if they move to other tools for additional triples (or instances, class definitions, rules or whatever), they can stay in SHC format without losing data.

**Comment by VladimirAlexiev** [comment]
@HolgerKnublauch That's a good idea but maybe we should put them into some sort of container (maybe a graph?)

Can you describe which shacl triples are missing from SHACLC?

**Comment by VladimirAlexiev** [comment]
https://github.com/VladimirAlexiev/shaclc-mode

**Comment by HolgerKnublauch** [comment]
The triples that are missing are those that are typically found in ontologies. Examples include annotations on classes, their exact rdf:type, OWL axioms, global rdf property definitions, enumerated instances, their properties etc. It can really be anything, and I believe SHACLC will have a much stronger story to tell if it can round-trip those files without loss of data.

**Comment by VladimirAlexiev** [comment]
@HolgerKnublauch What do you think of these:
- https://gitlab.com/allotrope-open-source/shape-editor
- it says it uses https://gitlab.com/osthus-afo/shaclc but that is gone...

**Comment by HolgerKnublauch** [comment]
I don't know these projects.

**Comment by VladimirAlexiev** [comment]
@HolgerKnublauch (unrelated): Where is the source of http://datashapes.org/constraints.html ? Want to add dash:valueIn

**Comment by VladimirAlexiev** [comment]
https://gitlab.com/allotrope-open-source/shape-editor/-/blob/master/src/com.osthus.shapes.shaclc.parent/com.osthus.shapes.shaclc/src/com/osthus/shapes/shaclc/SHACLC.xtext shows they extend SHACLC with rules, incl SPARQL... 
https://www.allotrope.org/ is a big foundation in the life sciences / scientific data.

**Comment by HolgerKnublauch** [comment]
The datashapes.org files are in a private repo. Feel free to download the source and send me the updated section.

**Comment by HolgerKnublauch** [comment]
On the other topic, I would be perfectly fine with some container like

`graph {
    ...
}`

at the end of a SHC document to contain random Turtle triples. Maybe even with a configurable serialization such as JSON-LD. This wouldn't be hard to implement for a Reader, but the work would be to adjust the Writer to remember which triples have already been expressed by the Compacy Syntax.

**Comment by afs** [comment]
The Allotrope extended SHACLC looks interesting.

Something I'd like to see would be syntax for RDFS for `subClassOf` and `subPropertyOf` so that such declarations are in the SHACLC file.

```
    my:SpecialClass SubClassOf general:Class 
    my:specialProperty SubPropertyOf general:property
```

**Comment by HolgerKnublauch** [comment]
Wouldn't a generic insertion point for, say, Turtle be covering those special cases? 

(I am surprised subClassOf isn's already covered in the current SHACLC for shapeClasses - it could probably be shapeClass ex:Person extends ex:Animal, owl:Thing).

**Comment by afs** [comment]
Yes - general triples would work but I am finding that it is a common usage so aligned syntax is nicer - less about the triples which is what SHACLC is valuable for.

Re: shapeClass - that's one design pattern. I think SubClassOf/SubPropertyOf isn't specifc to that pattern. Of course, you can SubClassOf if there is `extends` with an empty `{}` but that seems artificial.

**Comment by VladimirAlexiev** [comment]
Copying from the linked issue: 

two implementations : TopBraid (April 2020)  and Apache Jena (July 2020), https://jena.apache.org/documentation/shacl/

**Comment by HolgerKnublauch** [comment]
Closing old issue as this library no longer contains SHACLC.
